tap 'caskroom/cask'
cask 'dropbox'
brew 'python'
brew 'rbenv'
brew 'ruby-build'
brew 'node'
brew 'wget'
brew 'reattach-to-user-namespace'
brew 'tmux'
brew 'git'
brew 'fish'
brew 'brew-cask'
tap 'peco/peco'
brew 'peco'
cask 'karabiner'
cask 'slate'
brew 'macvim' # need xcode
