#!/usr/bin/env bash
ln -sfn $PWD/git_template ~/.git_template
ln -sf $PWD/gitconfig ~/.gitconfig
ln -sf $PWD/gitignore_global ~/.gitignore_global
if not test -e ~/.gitconfig.local
  cp $PWD/gitconfig.local.sample ~/.gitconfig.local
end

ln -sfn $PWD/ctags ~/.ctags
ln -sf $PWD/tmux.conf ~/.tmux.conf

ln -sf $PWD/bashrc ~/.bashrc
ln -sf $PWD/inputrc ~/.inputrc
ln -sfn $PWD/vim ~/.vim
ln -sf $PWD/vimrc ~/.vimrc

ln -sf $PWD/slate ~/.slate

ln -sf $PWD/gemrc ~/.gemrc

ln -sf $PWD/irbrc ~/.irbrc
ln -sf $PWD/pryrc ~/.pryrc
ln -sf $PWD/powconfig ~/.powconfig
ln -sf $PWD/hyper.js  ~/.hyper.js

ln -sf $PWD/eslintrc.json ~/.eslintrc.json

ln -sfn $PWD/fish ~/.config/fish
ln -sf $PWD/private.xml "~/Library/Application\ Support/Karabiner/private.xml"
