#!/bin/bash
function man() {
  if [[ $# -eq 0 ]]; then
    WORD="$(command man -aWS 1 \* 2> /dev/null |
      xargs basename |
      sed 's/-[^-]*$//' |
      sed 's/[.0-9]*$//' |
      sort -u |
      fzf)"
    command man "$WORD"
  else
    command man "$@"
  fi
}
