#!/bin/bash

function main() {
  target=$(rg -N "^\[.+\]$" ~/.aws/credentials | grep -v "\[default\]" | fzf | sed -e 's/\[/\\[/g' | sed -e 's/]/\\]/g')
  lines=()

  while IFS='' read -r line; do
    lines+=("$line")
  done < <(rg -N -A 2 "$target" ~/.aws/credentials)

  while IFS='' read -r line; do
    lines+=("$line")
  done < <(sed -e '/\[default\]/,/aws_secret_access_key/d' ~/.aws/credentials)

  lines[0]="[default]"

  printf "%s\n" "${lines[@]}" >~/.aws/credentials
}
main "$@"
