#!/bin/bash
set -ex -o pipefail

function main() {
  TARGET=$(rg -N "^\[.+\]$" ~/.aws/credentials | grep -v "\[default\]" | fzf | sed -e 's/\[/\\[/g' | sed -e 's/]/\\]/g')
  LINES=()

  while IFS='' read -r LINE; do
    LINES+=("$LINE")
  done < <(rg -N -A 2 "$TARGET" ~/.aws/credentials)

  while IFS='' read -r LINE; do
    LINES+=("$LINE")
  done < <(sed -e '/\[default\]/,/aws_secret_access_key/d' ~/.aws/credentials)

  LINES[0]="[default]"

  printf "%s\n" "${LINES[@]}" >~/.aws/credentials
}
main "$@"
