#!/bin/bash
set -ex -o pipefail

function main() {
  if [[ $# -eq 0 ]]; then
    WORD="$(command man -aWS 1 \* 2> /dev/null |
      xargs basename |
      sed 's/-[^-]*$//' |
      sed 's/[.0-9]*$//' |
      sort -u |
      fzf)"
  else
    WORD="$*"
  fi
  open "dash://$WORD"
}
main "$@"
