#!/bin/bash
set -ex -o pipefail

function main() {
  PREVIEW="bat --style=numbers,changes --color=always {} | head -n 20"
  fd "$@" | \
    fzf --height 80% --preview "$PREVIEW" --layout reverse \
        --preview-window up,20,border-horizontal | \
    xargs nvim
}
main "$@"
