#!/bin/bash
set -ex -o pipefail

function main() {
  LINE=$(ps aux | fzf)
  PROCESS_NAME=$(echo "$LINE" | awk '{print $11}')
  PID=$(echo "$LINE" | awk '{print $2}')
  kill -9 "$PID"
  echo
  echo " (╯°□°）╯︵ $(echo "$PROCESS_NAME" | flip 2>/dev/null)"
  echo
}
main "$@"
