#!/bin/bash
set -ex -o pipefail

function main() {
  if [[ $# -eq 0 ]]; then
    PREVIEW="git show --color=always {-1}"
    git branch | \
      fzf --height 80% --preview "$PREVIEW" --layout reverse \
          --preview-window up,20,border-horizontal | \
      xargs git branch -D
  else
    git branch -D "$@"
  fi
}
main "$@"
