#!/bin/bash
function main() {
  if [[ $# -eq 0 ]]; then
    echo "git branch | fzf --height 40% --border | xargs git restore"
    git branch | fzf --height 40% --border | xargs git restore
  else
    echo "git restore $*"
    git restore "$@"
  fi
}
main "$@"
