#!/bin/bash
set -ex -o pipefail

function main() {
  if [[ $# -eq 0 ]]; then
    preview="git diff --color=always -- {-1}"
    git status --porcelain | \
      awk '{print $2}' | \
      fzf  --height 80% --preview "$preview" --layout reverse \
           --preview-window up,20,border-horizontal | \
      xargs git restore
  else
    git restore "$@"
  fi
}
main "$@"
