#!/bin/bash
set -ex -o pipefail

function main() {
  if [[ $# -eq 0 ]]; then
    jq -r '.scripts | keys[]' package.json | fzf --height 40% --border | xargs npm run
  else
    npm run "$@"
  fi
}
main "$@"
