#!/bin/bash
set -ex -o pipefail

function main() {
  if [ $# = 0 ]; then
    usage
  fi

  public_ips=()
  split_list=()

  while IFS='' read -r line; do
    public_ips+=("$line")
  done < <(get-all-ec2-instance-public-ips)

  for ip in "${public_ips[@]:1}"; do
    split_list+=(split-pane ssh -i "$*" "ec2-user@$ip" ';')
  done

  tmux new-session -s "aws" -d ssh -i "$*" "ec2-user@${public_ips[0]}" ';' \
    "${split_list[@]}" \
    select-layout tiled ';' \
    set-option -w synchronize-panes ';' \
    attach-session -d -t aws
}

function usage() {
cat <<_EOT_
Usage:
  "${0##*/} [private RSA key path]
_EOT_
exit 1
}

main "$@"
