#!/bin/bash
set -ex -o pipefail

function main() {
  if [ $# = 0 ]; then
    usage
  fi

  PUBLIC_IPS=()
  SPLIT_LIST=()

  while IFS='' read -r LINE; do
    PUBLIC_IPS+=("$LINE")
  done < <(get-all-ec2-instance-public-ips)

  for IP in "${PUBLIC_IPS[@]:1}"; do
    SPLIT_LIST+=(split-pane ssh -i "$*" "ec2-user@$IP" ';')
  done

  tmux new-session -s "aws" -d ssh -i "$*" "ec2-user@${PUBLIC_IPS[0]}" ';' \
    "${SPLIT_LIST[@]}" \
    select-layout tiled ';' \
    set-option -w synchronize-panes ';' \
    attach-session -d -t aws
}

function usage() {
cat <<_EOT_
Usage:
  "${0##*/} [private RSA key path]
_EOT_
exit 2
}

main "$@"
