#!/bin/bash
set -ex -o pipefail

function main() {
  TOGGLE=$HOME/.toggle_dark

  if [ ! -e "$TOGGLE" ]; then
    touch "$TOGGLE"
    echo -ne "\033]50;SetProfile=Dark\a"
  else
    rm "$TOGGLE"
    echo -ne "\033]50;SetProfile=Default\a"
  fi
  osascript -e 'tell app "System Events" to tell appearance preferences to set dark mode to not dark mode'
}
main "$@"
