#!/bin/bash

function main() {
  toggle=$HOME/.toggle_dark

  if [ ! -e "$toggle" ]; then
    touch "$toggle"
    echo -ne "\033]50;SetProfile=Dark\a"
  else
    rm "$toggle"
    echo -ne "\033]50;SetProfile=Default\a"
  fi
}
main "$@"
osascript -e 'tell app "System Events" to tell appearance preferences to set dark mode to not dark mode'
