#!/bin/bash
set -ex -o pipefail

function main() {
  if [[ $# -eq 1 ]]; then
    unset PATH
    for _ in $(seq 1 "$1"); do
      PATH="$PATH../"
    done
    cd "$PATH" || return 0
  else
    usage
  fi
}

function usage() {
cat <<_EOT_
Usage:
  ${0##*/} [number]

Description:
  cd .. N times
_EOT_
exit 2
}

main "$@"
