#!/bin/bash

function update-asdf {
  echo updating asdf
  asdf update
  asdf plugin-update --all
}

function update-apt-get {
  echo updating apt-get
  sudo apt-get update -y
}

function update-brew {
  echo updating brew
  brew update
  brew upgrade --all
  brew cleanup
}

function update-vim {
  echo updating vim
  vim +PackUpdate +qall
}
function update-yarn {
  if [[ $VERSION ]]; then
    echo updating yarn to $VERSION
    npm install -g "https://yarnpkg.com/downloads/${VERSION}/yarn-v${VERSION}.tar.gz"
  else
    echo updating yarn to latest
    npm install -g "https://yarnpkg.com/latest.tar.gz"
  fi
  asdf reshim nodejs
}

function update-npm {
  echo updating npm
  npm i -g npm
}

function update-dotfiles {
  echo updating dotfiles
  pushd ~/dotfiles
  git pull
  popd
}

function update-kuromoji {
  echo updating kuromoji
  brew services stop elasticsearch
  elasticsearch-plugin install analysis-kuromoji
  brew services start elasticsearch
}

case $1 in
aset)
  update-asdf
  ;;
asdf)
  update-asdf
  ;;
apt-get)
  update-apt-get
  ;;
brew)
  update-brew
  ;;
dotfiles)
  update-dotfiles
  ;;
npm)
  update-npm
  ;;
kuromoji)
  update-kuromoji
  ;;
vim)
  update-vim
  ;;
yarn)
  update-yarn
  ;;
all)
  update-asdf
  update-brew
  update-dotfiles
  update-npm
  update-vim
  ;;
*)
  echo 'update what?'
  echo 'please select from:
  apt-get, asdf, brew, dotfiles, kuromoji, npm, vim, yarn, all'
  ;;
esac

