#!/bin/bash
set -ex -o pipefail

function update-asdf() {
  echo updating asdf
  asdf update
  asdf plugin-update --all
}

function update-apt-get() {
  echo updating apt-get
  sudo apt-get update -y
}

function update-brew() {
  echo updating brew
  brew update
  brew upgrade
  brew cleanup
}

function update-vim() {
  echo updating vim
  nvim -c 'call minpac#update("", {"do": "quit | quit"})'
}
function update-yarn() {
  if [[ $VERSION ]]; then
    echo "updating yarn to $VERSION"
    npm install -g "https://yarnpkg.com/downloads/$VERSION/yarn-v$VERSION.tar.gz"
  else
    echo updating yarn to latest
    npm install -g "https://yarnpkg.com/latest.tar.gz"
  fi
  asdf reshim nodejs
}

function update-npm() {
  echo updating npm
  npm i -g npm
}

function update-dotfiles() {
  echo updating dotfiles
  pushd ~/dotfiles || return
  if [[ $(git diff --stat) != '' ]]; then
    echo 'it is dirty'
    git stash
    git pull
    git stash pop
  else
    echo 'clean'
    git pull
  fi
  popd || return
}

function update-kuromoji() {
  echo updating kuromoji
  brew services stop elasticsearch
  elasticsearch-plugin remove analysis-kuromoji
  elasticsearch-plugin install analysis-kuromoji
  brew services start elasticsearch
}

function list-all() {
echo '
apt-get
asdf
brew
dotfiles
kuromoji
npm
vim
yarn
all' | fzf --height 40% --border
}

function main() {
  if [[ $# -eq 0 ]]; then
    TARGET=$(list-all)
  else
    TARGET=$1
  fi

  case $TARGET in
  aset)
    update-asdf
    ;;
  asdf)
    update-asdf
    ;;
  apt-get)
    update-apt-get
    ;;
  brew)
    update-brew
    ;;
  dotfiles)
    update-dotfiles
    ;;
  npm)
    update-npm
    ;;
  kuromoji)
    update-kuromoji
    ;;
  vim)
    update-vim
    ;;
  yarn)
    update-yarn
    ;;
  all)
    update-asdf
    update-brew
    update-dotfiles
    update-npm
    update-vim
    ;;
  *)
    usage
    ;;
  esac
}

function usage() {
cat <<_EOT_
Usage:
  ${0##*/} [target]

Description:
  Update target.
  target could be one of apt-get, asdf, brew, dotfiles, kuromoji, npm, vim, yarn
  or all
_EOT_
exit 2
}
main "$@"
