# aclocal-1: Deroffing man parser
# Autogenerated from man pages
complete -c aclocal-1 -l automake-acdir --description 'directory holding automake-provided m4 files'
complete -c aclocal-1 -l system-acdir --description 'directory holding third-party system-wide fil... [See Man Page]'
complete -c aclocal-1 -l 'diff[' --description 'run COMMAND [diff -u] on M4 files that would ... [See Man Page]'
complete -c aclocal-1 -l dry-run --description 'pretend to, but do not actually update any fi... [See Man Page]'
complete -c aclocal-1 -l force --description 'always update output file'
complete -c aclocal-1 -l help --description 'print this help, then exit'
complete -c aclocal-1 -s I --description 'add directory to search list for '
complete -c aclocal-1 -l install --description 'copy third-party files to the first -I direct... [See Man Page]'
complete -c aclocal-1 -l output --description 'put output in FILE (default aclocal'
complete -c aclocal-1 -l print-ac-dir --description 'print name of directory holding system-wide t... [See Man Page]'
complete -c aclocal-1 -l verbose --description 'don\'t be silent'
complete -c aclocal-1 -l version --description 'print version number, then exit'
complete -c aclocal-1 -s W -l warnings --description 'report the warnings falling in CATEGORY '

