# acyclic: Deroffing man parser
# Autogenerated from man pages
complete -c acyclic -s n --description 'No output is produced, though the return valu... [See Man Page]'
complete -c acyclic -s v --description 'Print information about whether the file is a... [See Man Page]'
complete -c acyclic -s o --description 'causes the output to be written to the specif... [See Man Page]'
complete -c acyclic -s '?' --description 'option causes the program to print usage info... [See Man Page]'

