# apxs: Type1
# Autogenerated from man pages
complete -c apxs -s n --description 'This explicitly sets the module name for the ... [See Man Page]'
complete -c apxs -s q --description 'Performs a query for apxs\'s knowledge about c... [See Man Page]'
complete -c apxs -s S --description 'This option changes the apxs settings describ... [See Man Page]'
complete -c apxs -s g --description 'This generates a subdirectory name (see optio... [See Man Page]'
complete -c apxs -s c --description 'This indicates the compilation operation'
complete -c apxs -s o --description 'Explicitly specifies the filename of the crea... [See Man Page]'
complete -c apxs -s D --description 'This option is directly passed through to the... [See Man Page]'
complete -c apxs -s I --description 'This option is directly passed through to the... [See Man Page]'
complete -c apxs -s L --description 'This option is directly passed through to the... [See Man Page]'
complete -c apxs -s l --description 'This option is directly passed through to the... [See Man Page]'
complete -c apxs -o Wc --description 'This option passes compiler-flags as addition... [See Man Page]'
complete -c apxs -o Wl --description 'This option passes linker-flags as additional... [See Man Page]'
complete -c apxs -s i --description 'This indicates the installation operation and... [See Man Page]'
complete -c apxs -s a --description 'This activates the module by automatically ad... [See Man Page]'
complete -c apxs -s A --description 'Same as option -a but the created LoadModule ... [See Man Page]'

