# asctl: Darwin man parser
# Autogenerated from man pages
complete -c asctl -s p --description 'By default,'
complete -c asctl -l -container-path --description 'The --container-path option specifies a path ... [See Man Page]'

