# asn1parse: Type1
# Autogenerated from man pages
complete -c asn1parse -o inform --description 'the input format'
complete -c asn1parse -o in --description 'the input file, default is standard input'
complete -c asn1parse -o out --description 'output file to place the \\s-1DER\\s0 encoded d... [See Man Page]'
complete -c asn1parse -o noout --description 'don\'t output the parsed version of the input ... [See Man Page]'
complete -c asn1parse -o offset --description 'starting offset to begin parsing, default is ... [See Man Page]'
complete -c asn1parse -o length --description 'number of bytes to parse, default is until en... [See Man Page]'
complete -c asn1parse -s i --description 'indents the output according to the \\*(L"dept... [See Man Page]'
complete -c asn1parse -o oid --description 'a file containing additional \\s-1OBJECT\\s0 ID... [See Man Page]'
complete -c asn1parse -o strparse --description 'parse the contents octets of the \\s-1ASN\\s0'

