# automake-1: Deroffing man parser
# Autogenerated from man pages
complete -c automake-1 -l help --description 'print this help, then exit'
complete -c automake-1 -l version --description 'print version number, then exit'
complete -c automake-1 -s v -l verbose --description 'verbosely list files processed'
complete -c automake-1 -l no-force --description 'only update Makefile'
complete -c automake-1 -s W -l warnings --description 'report the warnings falling in CATEGORY '
complete -c automake-1 -s i -l ignore-deps --description 'disable dependency tracking code'
complete -c automake-1 -l include-deps --description 'enable dependency tracking code '
complete -c automake-1 -l foreign --description 'set strictness to foreign'
complete -c automake-1 -l gnits --description 'set strictness to gnits'
complete -c automake-1 -l gnu --description 'set strictness to gnu '
complete -c automake-1 -s a -l add-missing --description 'add missing standard files to package'
complete -c automake-1 -l libdir --description 'set directory storing library files'
complete -c automake-1 -l print-libdir --description 'print directory storing library files'
complete -c automake-1 -s c -l copy --description 'with -a, copy missing files (default is symli... [See Man Page]'
complete -c automake-1 -s f -l force-missing --description 'force update of standard files '

