# bcomps: Deroffing man parser
# Autogenerated from man pages
complete -c bcomps -s s --description 'No output graph is printed'
complete -c bcomps -s t --description 'Print the underlying block-cutvertex tree'
complete -c bcomps -s x --description 'Each biconnected component is printed as a se... [See Man Page]'
complete -c bcomps -s v --description 'Prints number of blocks and cutvertices'
complete -c bcomps -s o --description 'If specified, each root graph will be written... [See Man Page]'

