# bdftopcf: Deroffing man parser
# Autogenerated from man pages
complete -c bdftopcf -o pn --description 'Sets the font glyph padding'
complete -c bdftopcf -o un --description 'Sets the font scanline unit'
complete -c bdftopcf -s m --description 'Sets the font bit order to MSB (most signific... [See Man Page]'
complete -c bdftopcf -s l --description 'Sets the font bit order to LSB (least signifi... [See Man Page]'
complete -c bdftopcf -s M --description 'Sets the font byte order to MSB first'
complete -c bdftopcf -s L --description 'Sets the font byte order to LSB first'
complete -c bdftopcf -s t --description 'When this option is specified,  bdftopcf will... [See Man Page]'
complete -c bdftopcf -s i --description 'This option inhibits the normal computation o... [See Man Page]'
complete -c bdftopcf -s o --description 'By default bdftopcf writes the pcf file to st... [See Man Page]'

