# bison: Deroffing man parser
# Autogenerated from man pages
complete -c bison -s b
complete -c bison -l file-prefix --description 'Specify a prefix to use for all  bison output... [See Man Page]'
complete -c bison -s d
complete -c bison -l defines --description 'The behavior of  --defines is the same than  ... [See Man Page]'
complete -c bison -s g
complete -c bison -l graph --description 'The behavior of  --graph is the same than  -g... [See Man Page]'
complete -c bison -s k
complete -c bison -l token-table --description 'This switch causes the B name '
complete -c bison -s l
complete -c bison -l no-lines --description 'Don\'t put any  #line preprocessor commands in... [See Man Page]'
complete -c bison -s n
complete -c bison -l no-parser --description 'Do not generate the parser code into the outp... [See Man Page]'
complete -c bison -s o
complete -c bison -l output-file --description 'Specify the name  outfile for the parser file... [See Man Page]'
complete -c bison -s p
complete -c bison -l name-prefix --description 'Rename the external symbols used in the parse... [See Man Page]'
complete -c bison -s t
complete -c bison -l debug --description 'In the parser file, define the macro  YYDEBUG... [See Man Page]'
complete -c bison -s v
complete -c bison -l verbose --description 'Write an extra output file containing verbose... [See Man Page]'
complete -c bison -s V
complete -c bison -l version --description 'Print the version number of  bison and exit'
complete -c bison -s h
complete -c bison -l help --description 'Print a summary of the options to  bison and ... [See Man Page]'
complete -c bison -s y
complete -c bison -l yacc
complete -c bison -l fixed-output-files --description 'Equivalent to'

