# ccomps: Deroffing man parser
# Autogenerated from man pages
complete -c ccomps -s e --description 'Do not induce edges in the connected componen... [See Man Page]'
complete -c ccomps -s s --description 'No output graph is printed'
complete -c ccomps -s x --description 'Only the connected components are printed, as... [See Man Page]'
complete -c ccomps -s v --description 'Counts of nodes, edges and connected componen... [See Man Page]'
complete -c ccomps -s z --description 'Sort components by size, with the largest fir... [See Man Page]'
complete -c ccomps -s C --description 'Use clusters in computing components in addit... [See Man Page]'
complete -c ccomps -s n --description 'Do not project subgraph structure'
complete -c ccomps -s X --description 'Prints only the component containing the node... [See Man Page]'
complete -c ccomps -o 'X#' --description 'Prints only components in the given range'
complete -c ccomps -s o --description 'If specified, each graph will be written to a... [See Man Page]'

