# circo: Deroffing man parser
# Autogenerated from man pages
complete -c circo -o Tps
complete -c circo -o Tsvg -o Tsvgz
complete -c circo -o Tfig
complete -c circo -o Tmif
complete -c circo -o Thpgl -o Tpcl
complete -c circo -o Tpng -o Tgif
complete -c circo -o Tdia
complete -c circo -o Timap --description 'that has a non-null "href" attribute'
complete -c circo -o Tcmapx --description 'Additional less common or more special-purpos... [See Man Page]'
complete -c circo -s G
complete -c circo -s N
complete -c circo -s E --description 'Example: -Gsize="7,8" -Nshape=box -Efontsize=... [See Man Page]'
complete -c circo -o lfile --description 'Usually these define custom shapes or styles'
complete -c circo -o Tlang
complete -c circo -o 'n[1' --description 'If set, neato assumes nodes have already been... [See Man Page]'
complete -c circo -o Klayout
complete -c circo -s O -s T
complete -c circo -s P
complete -c circo -s v
complete -c circo -s V
complete -c circo -s '?' --description EXAMPLES

