# cluster: Deroffing man parser
# Autogenerated from man pages
complete -c cluster -s C --description 'specifies a targeted number of clusters that ... [See Man Page]'
complete -c cluster -s o --description 'Specifies that output should go into the file... [See Man Page]'
complete -c cluster -s v --description 'Verbose mode'

