# clusterdb: Deroffing man parser
# Autogenerated from man pages
complete -c clusterdb -s a -l all --description 'Cluster all databases'
complete -c clusterdb -s e -l echo --description 'Echo the commands that clusterdb generates an... [See Man Page]'
complete -c clusterdb -s q -l quiet --description 'Do not display progress messages'
complete -c clusterdb -s t -l table --description 'Cluster table only'
complete -c clusterdb -s v -l verbose --description 'Print detailed information during processing'
complete -c clusterdb -s V -l version --description 'Print the clusterdb version and exit'
complete -c clusterdb -s '?' -l help --description 'Show help about clusterdb command line argume... [See Man Page]'
complete -c clusterdb -s h -l host --description 'Specifies the host name of the machine on whi... [See Man Page]'
complete -c clusterdb -s p -l port --description 'Specifies the TCP port or local Unix domain s... [See Man Page]'
complete -c clusterdb -s U -l username --description 'User name to connect as'
complete -c clusterdb -s w -l no-password --description 'Never issue a password prompt'
complete -c clusterdb -s W -l password --description 'Force clusterdb to prompt for a password befo... [See Man Page]'
complete -c clusterdb -l 'all)' --description PGDATABASE

