# couchjs: Deroffing man parser
# Autogenerated from man pages
complete -c couchjs -s h --description 'display a short help message and exit'
complete -c couchjs -s V --description 'display version information and exit'
complete -c couchjs -s H --description 'enable couchjs cURL bindings (only avaiable i... [See Man Page]'
complete -c couchjs -s S --description 'specify that the interpreter should set the s... [See Man Page]'

