# couchdb: Deroffing man parser
# Autogenerated from man pages
complete -c couchdb -s h --description 'display a short help message and exit'
complete -c couchdb -s V --description 'display version information and exit'
complete -c couchdb -s a --description 'add configuration FILE to chain'
complete -c couchdb -s A --description 'add configuration DIR to chain'
complete -c couchdb -s n --description 'reset configuration file chain (including sys... [See Man Page]'
complete -c couchdb -s c --description 'print configuration file chain and exit'
complete -c couchdb -s i --description 'use the interactive Erlang shell'
complete -c couchdb -s b --description 'spawn as a background process'
complete -c couchdb -s p --description 'set the background PID FILE (overrides system... [See Man Page]'
complete -c couchdb -s r --description 'respawn background process after SECONDS (def... [See Man Page]'
complete -c couchdb -s o --description 'redirect background stdout to FILE (defaults ... [See Man Page]'
complete -c couchdb -s e --description 'redirect background stderr to FILE (defaults ... [See Man Page]'
complete -c couchdb -s s --description 'display the status of the background process'
complete -c couchdb -s k --description 'kill the background process, will respawn if ... [See Man Page]'
complete -c couchdb -o os_mon --description 'start_memsup false     start_cpu_sup false   ... [See Man Page]'
complete -c couchdb -s d --description 'shutdown the background process REPORTING BUG... [See Man Page]'

