# createdb: Deroffing man parser
# Autogenerated from man pages
complete -c createdb -s D -l tablespace --description 'Specifies the default tablespace for the data... [See Man Page]'
complete -c createdb -s e -l echo --description 'Echo the commands that createdb generates and... [See Man Page]'
complete -c createdb -s E -l encoding --description 'Specifies the character encoding scheme to be... [See Man Page]'
complete -c createdb -s l -l locale --description 'Specifies the locale to be used in this datab... [See Man Page]'
complete -c createdb -l lc-collate --description 'Specifies the LC_COLLATE setting to be used i... [See Man Page]'
complete -c createdb -l lc-ctype --description 'Specifies the LC_CTYPE setting to be used in ... [See Man Page]'
complete -c createdb -s O -l owner --description 'Specifies the database user who will own the ... [See Man Page]'
complete -c createdb -s T -l template --description 'Specifies the template database from which to... [See Man Page]'
complete -c createdb -s V -l version --description 'Print the createdb version and exit'
complete -c createdb -s '?' -l help --description 'Show help about createdb command line argumen... [See Man Page]'
complete -c createdb -s h -l host --description 'Specifies the host name of the machine on whi... [See Man Page]'
complete -c createdb -s p -l port --description 'Specifies the TCP port or the local Unix doma... [See Man Page]'
complete -c createdb -s U -l username --description 'User name to connect as'
complete -c createdb -s w -l no-password --description 'Never issue a password prompt'
complete -c createdb -s W -l password --description 'Force createdb to prompt for a password befor... [See Man Page]'
complete -c createdb -l 'lc-ctype.'

