# createlang: Deroffing man parser
# Autogenerated from man pages
complete -c createlang -s e -l echo --description 'Display SQL commands as they are executed'
complete -c createlang -s l -l list --description 'Show a list of already installed languages in... [See Man Page]'
complete -c createlang -s V -l version --description 'Print the createlang version and exit'
complete -c createlang -s '?' -l help --description 'Show help about createlang command line argum... [See Man Page]'
complete -c createlang -s h -l host --description 'Specifies the host name of the machine on whi... [See Man Page]'
complete -c createlang -s p -l port --description 'Specifies the TCP port or local Unix domain s... [See Man Page]'
complete -c createlang -s U -l username --description 'User name to connect as'
complete -c createlang -s w -l no-password --description 'Never issue a password prompt'
complete -c createlang -s W -l password --description 'Force createlang to prompt for a password bef... [See Man Page]'

