# ct_run: Deroffing man parser
# Autogenerated from man pages
complete -c ct_run -o erl_args --description 'it\'s possible to divide the options on the ct... [See Man Page]'
complete -c ct_run -o help --description 'it prints all valid start flags to stdout'

