# ctags: Darwin man parser
# Autogenerated from man pages
complete -c ctags -s a --description 'append to'
complete -c ctags -s B --description 'use backward searching patterns'
complete -c ctags -s d --description 'create tags for'
complete -c ctags -s F --description 'use forward searching patterns'
complete -c ctags -s f --description 'Places the tag descriptions in a file called'
complete -c ctags -s t --description 'create tags for typedefs, structs, unions, an... [See Man Page]'
complete -c ctags -s u --description 'update the specified files in the'
complete -c ctags -s v --description 'An index of the form expected by'
complete -c ctags -s w --description 'suppress warning diagnostics'
complete -c ctags -s x

