# cvt: Deroffing man parser
# Autogenerated from man pages
complete -c cvt -s v -l verbose --description 'Warn verbosely when a given mode does not com... [See Man Page]'
complete -c cvt -s r -l reduced --description 'Create a mode with reduced blanking'

