# db_archive: Darwin man parser
# Autogenerated from man pages
complete -c db_archive -s a --description 'Write all pathnames as absolute pathnames, in... [See Man Page]'
complete -c db_archive -s d --description 'Remove log files that are no longer needed; n... [See Man Page]'
complete -c db_archive -s h --description 'Specify a home directory for the database env... [See Man Page]'
complete -c db_archive -s l --description 'Write out the pathnames of all the database l... [See Man Page]'
complete -c db_archive -s P --description 'Specify an environment password'
complete -c db_archive -s s --description 'Write the pathnames of all the database files... [See Man Page]'
complete -c db_archive -s V --description 'Write the library version number to the stand... [See Man Page]'
complete -c db_archive -s v --description 'Run in verbose mode, listing the checkpoints ... [See Man Page]'

