# db_checkpoint: Darwin man parser
# Autogenerated from man pages
complete -c db_checkpoint -s 1 --description 'Checkpoint the log once, regardless of whethe... [See Man Page]'
complete -c db_checkpoint -s h --description 'Specify a home directory for the database env... [See Man Page]'
complete -c db_checkpoint -s k --description 'Checkpoint the database at least as often as ... [See Man Page]'
complete -c db_checkpoint -s L --description 'Log the execution of the db_checkpoint utilit... [See Man Page]'
complete -c db_checkpoint -s P --description 'Specify an environment password'
complete -c db_checkpoint -s p --description 'Checkpoint the database at least every min mi... [See Man Page]'
complete -c db_checkpoint -s V --description 'Write the library version number to the stand... [See Man Page]'
complete -c db_checkpoint -s v --description 'Write the time of each checkpoint attempt to ... [See Man Page]'

