# db_dump: Darwin man parser
# Autogenerated from man pages
complete -c db_dump -s d --description 'Dump the specified database in a format helpf... [See Man Page]'
complete -c db_dump -s f --description 'Write to the specified file instead of to the... [See Man Page]'
complete -c db_dump -s h --description 'Specify a home directory for the database env... [See Man Page]'
complete -c db_dump -s k --description 'Dump record numbers from Queue and Recno data... [See Man Page]'
complete -c db_dump -s l --description 'List the databases stored in the file'
complete -c db_dump -s N --description 'Do not acquire shared region mutexes while ru... [See Man Page]'
complete -c db_dump -s P --description 'Specify an environment password'
complete -c db_dump -s p --description 'If characters in either the key or data items... [See Man Page]'
complete -c db_dump -s R --description 'Aggressively salvage data from a possibly cor... [See Man Page]'
complete -c db_dump -s r --description 'Salvage data from a possibly corrupt file'
complete -c db_dump -s s --description 'Specify a single database to dump'
complete -c db_dump -s V --description 'Write the library version number to the stand... [See Man Page]'

