# db_deadlock: Darwin man parser
# Autogenerated from man pages
complete -c db_deadlock -s a --description 'When a deadlock is detected, abort the locker... [See Man Page]'
complete -c db_deadlock -s h --description 'Specify a home directory for the database env... [See Man Page]'
complete -c db_deadlock -s L --description 'Log the execution of the db_deadlock utility ... [See Man Page]'
complete -c db_deadlock -s t --description 'Check the database environment every sec seco... [See Man Page]'
complete -c db_deadlock -s V --description 'Write the library version number to the stand... [See Man Page]'
complete -c db_deadlock -s v --description 'Run in verbose mode, generating messages each... [See Man Page]'

