# db_load: Darwin man parser
# Autogenerated from man pages
complete -c db_load -s c --description 'Specify configuration options ignoring any va... [See Man Page]'
complete -c db_load -s f --description 'Read from the specified input file instead of... [See Man Page]'
complete -c db_load -s h --description 'Specify a home directory for the database env... [See Man Page]'
complete -c db_load -s n --description 'Do not overwrite existing keys in the databas... [See Man Page]'
complete -c db_load -s P --description 'Specify an environment password'
complete -c db_load -s T --description 'The -T option allows non-Berkeley DB applicat... [See Man Page]'
complete -c db_load -s t --description 'Specify the underlying access method'
complete -c db_load -s V --description 'Write the library version number to the stand... [See Man Page]'

