# db_printlog: Darwin man parser
# Autogenerated from man pages
complete -c db_printlog -s h --description 'Specify a home directory for the database env... [See Man Page]'
complete -c db_printlog -s N --description 'Do not acquire shared region mutexes while ru... [See Man Page]'
complete -c db_printlog -s P --description 'Specify an environment password'
complete -c db_printlog -s r --description 'Read the log files in reverse order'
complete -c db_printlog -s V --description 'Write the library version number to the stand... [See Man Page]'

