# db_recover: Darwin man parser
# Autogenerated from man pages
complete -c db_recover -s c --description 'Perform catastrophic recovery instead of norm... [See Man Page]'
complete -c db_recover -s e --description 'Retain the environment after running recovery... [See Man Page]'
complete -c db_recover -s h --description 'Specify a home directory for the database env... [See Man Page]'
complete -c db_recover -s P --description 'Specify an environment password'
complete -c db_recover -s t --description 'Recover to the time specified rather than to ... [See Man Page]'
complete -c db_recover -s V --description 'Write the library version number to the stand... [See Man Page]'
complete -c db_recover -s v --description 'Run in verbose mode'

