# db_stat: Darwin man parser
# Autogenerated from man pages
complete -c db_stat -s C --description 'Display internal information about the lock r... [See Man Page]'
complete -c db_stat -s c --description 'Display lock region statistics, as described ... [See Man Page]'
complete -c db_stat -s d --description 'Display database statistics for the specified... [See Man Page]'
complete -c db_stat -s e --description 'Display current environment statistics'
complete -c db_stat -s f --description 'Display only those database statistics that c... [See Man Page]'
complete -c db_stat -s h --description 'Specify a home directory for the database env... [See Man Page]'
complete -c db_stat -s l --description 'Display log region statistics, as described i... [See Man Page]'
complete -c db_stat -s M --description 'Display internal information about the shared... [See Man Page]'
complete -c db_stat -s m --description 'Display shared memory buffer pool statistics,... [See Man Page]'
complete -c db_stat -s N --description 'Do not acquire shared region mutexes while ru... [See Man Page]'
complete -c db_stat -s P --description 'Specify an environment password'
complete -c db_stat -s r --description 'Display replication statistics, as described ... [See Man Page]'
complete -c db_stat -s s --description 'Display statistics for the specified database... [See Man Page]'
complete -c db_stat -s t --description 'Display transaction region statistics, as des... [See Man Page]'
complete -c db_stat -s V --description 'Write the library version number to the stand... [See Man Page]'
complete -c db_stat -s Z --description 'Reset the statistics after reporting them; va... [See Man Page]'

