# db_upgrade: Darwin man parser
# Autogenerated from man pages
complete -c db_upgrade -s h --description 'Specify a home directory for the database env... [See Man Page]'
complete -c db_upgrade -s N --description 'Do not acquire shared region mutexes while ru... [See Man Page]'
complete -c db_upgrade -s P --description 'Specify an environment password'
complete -c db_upgrade -s s --description 'This flag is only meaningful when upgrading d... [See Man Page]'
complete -c db_upgrade -s V --description 'Write the library version number to the stand... [See Man Page]'

