# db_verify: Darwin man parser
# Autogenerated from man pages
complete -c db_verify -s h --description 'Specify a home directory for the database env... [See Man Page]'
complete -c db_verify -s o --description 'Skip the database checks for btree and duplic... [See Man Page]'
complete -c db_verify -s N --description 'Do not acquire shared region mutexes while ru... [See Man Page]'
complete -c db_verify -s P --description 'Specify an environment password'
complete -c db_verify -s q --description 'Suppress the printing of any error descriptio... [See Man Page]'
complete -c db_verify -s V --description 'Write the library version number to the stand... [See Man Page]'

