# dhparam: Type1
# Autogenerated from man pages
complete -c dhparam -o inform --description 'This specifies the input format'
complete -c dhparam -o outform --description 'This specifies the output format, the options... [See Man Page]'
complete -c dhparam -o in --description 'This specifies the input filename to read par... [See Man Page]'
complete -c dhparam -o out --description 'This specifies the output filename parameters... [See Man Page]'
complete -c dhparam -o dsaparam --description 'If this option is used, \\s-1DSA\\s0 rather tha... [See Man Page]'
complete -c dhparam -s 2 -s 5 --description 'The generator to use, either 2 or 5'
complete -c dhparam -o rand --description 'a file or files containing random data used t... [See Man Page]'
complete -c dhparam -o noout --description 'this option inhibits the output of the encode... [See Man Page]'
complete -c dhparam -o text --description 'this option prints out the \\s-1DH\\s0 paramete... [See Man Page]'
complete -c dhparam -s C --description 'this option converts the parameters into C co... [See Man Page]'

