# diameter_compile: Deroffing man parser
# Autogenerated from man pages
complete -c diameter_compile -s o --description 'Write generated source to the specified direc... [See Man Page]'
complete -c diameter_compile -o E:
complete -c diameter_compile -o H: --description 'Supress erl and hrl generation, respectively'
complete -c diameter_compile -l name
complete -c diameter_compile -l prefix --description 'Set @name or @prefix to the specified string'
complete -c diameter_compile -l inherits --description 'Append @inherits of the specified module'

