# dot: Deroffing man parser
# Autogenerated from man pages
complete -c dot -o Tps
complete -c dot -o Tsvg -o Tsvgz
complete -c dot -o Tfig
complete -c dot -o Tmif
complete -c dot -o Thpgl -o Tpcl
complete -c dot -o Tpng -o Tgif
complete -c dot -o Tdia
complete -c dot -o Timap --description 'that has a non-null "href" attribute'
complete -c dot -o Tcmapx --description 'Additional less common or more special-purpos... [See Man Page]'
complete -c dot -s G
complete -c dot -s N
complete -c dot -s E --description 'Example: -Gsize="7,8" -Nshape=box -Efontsize=... [See Man Page]'
complete -c dot -o lfile --description 'Usually these define custom shapes or styles'
complete -c dot -o Tlang
complete -c dot -o 'n[1' --description 'If set, neato assumes nodes have already been... [See Man Page]'
complete -c dot -o Klayout
complete -c dot -s O -s T
complete -c dot -s P
complete -c dot -s v
complete -c dot -s V
complete -c dot -s '?' --description EXAMPLES

