# droplang: Deroffing man parser
# Autogenerated from man pages
complete -c droplang -s e -l echo --description 'Display SQL commands as they are executed'
complete -c droplang -s l -l list --description 'Show a list of already installed languages in... [See Man Page]'
complete -c droplang -s V -l version --description 'Print the droplang version and exit'
complete -c droplang -s '?' -l help --description 'Show help about droplang command line argumen... [See Man Page]'
complete -c droplang -s h -l host --description 'Specifies the host name of the machine on whi... [See Man Page]'
complete -c droplang -s p -l port --description 'Specifies the Internet TCP/IP port or local U... [See Man Page]'
complete -c droplang -s U -l username --description 'User name to connect as'
complete -c droplang -s w -l no-password --description 'Never issue a password prompt'
complete -c droplang -s W -l password --description 'Force droplang to prompt for a password befor... [See Man Page]'

