# dropdb: Deroffing man parser
# Autogenerated from man pages
complete -c dropdb -s e -l echo --description 'Echo the commands that dropdb generates and s... [See Man Page]'
complete -c dropdb -s i -l interactive --description 'Issues a verification prompt before doing any... [See Man Page]'
complete -c dropdb -s V -l version --description 'Print the dropdb version and exit'
complete -c dropdb -s '?' -l help --description 'Show help about dropdb command line arguments... [See Man Page]'
complete -c dropdb -s h -l host --description 'Specifies the host name of the machine on whi... [See Man Page]'
complete -c dropdb -s p -l port --description 'Specifies the TCP port or local Unix domain s... [See Man Page]'
complete -c dropdb -s U -l username --description 'User name to connect as'
complete -c dropdb -s w -l no-password --description 'Never issue a password prompt'
complete -c dropdb -s W -l password --description 'Force dropdb to prompt for a password before ... [See Man Page]'

