# dropuser: Deroffing man parser
# Autogenerated from man pages
complete -c dropuser -s e -l echo --description 'Echo the commands that dropuser generates and... [See Man Page]'
complete -c dropuser -s i -l interactive --description 'Prompt for confirmation before actually remov... [See Man Page]'
complete -c dropuser -s V -l version --description 'Print the dropuser version and exit'
complete -c dropuser -s '?' -l help --description 'Show help about dropuser command line argumen... [See Man Page]'
complete -c dropuser -s h -l host --description 'Specifies the host name of the machine on whi... [See Man Page]'
complete -c dropuser -s p -l port --description 'Specifies the TCP port or local Unix domain s... [See Man Page]'
complete -c dropuser -s U -l username --description 'User name to connect as (not the user name to... [See Man Page]'
complete -c dropuser -s w -l no-password --description 'Never issue a password prompt'
complete -c dropuser -s W -l password --description 'Force dropuser to prompt for a password befor... [See Man Page]'

