# dsaparam: Type1
# Autogenerated from man pages
complete -c dsaparam -o inform --description 'This specifies the input format'
complete -c dsaparam -o outform --description 'This specifies the output format, the options... [See Man Page]'
complete -c dsaparam -o in --description 'This specifies the input filename to read par... [See Man Page]'
complete -c dsaparam -o out --description 'This specifies the output filename parameters... [See Man Page]'
complete -c dsaparam -o noout --description 'this option inhibits the output of the encode... [See Man Page]'
complete -c dsaparam -o text --description 'this option prints out the \\s-1DSA\\s0 paramet... [See Man Page]'
complete -c dsaparam -s C --description 'this option converts the parameters into C co... [See Man Page]'
complete -c dsaparam -o genkey --description 'this option will generate a \\s-1DSA\\s0 either... [See Man Page]'
complete -c dsaparam -o rand --description 'a file or files containing random data used t... [See Man Page]'

