# ecparam: Type1
# Autogenerated from man pages
complete -c ecparam -o inform --description 'This specifies the input format'
complete -c ecparam -o outform --description 'This specifies the output format, the options... [See Man Page]'
complete -c ecparam -o in --description 'This specifies the input filename to read par... [See Man Page]'
complete -c ecparam -o out --description 'This specifies the output filename parameters... [See Man Page]'
complete -c ecparam -o noout --description 'This option inhibits the output of the encode... [See Man Page]'
complete -c ecparam -o text --description 'This option prints out the \\s-1EC\\s0 paramete... [See Man Page]'
complete -c ecparam -s C --description 'This option converts the \\s-1EC\\s0 parameters... [See Man Page]'
complete -c ecparam -o check --description 'Validate the elliptic curve parameters'
complete -c ecparam -o name --description 'Use the \\s-1EC\\s0 parameters with the specifi... [See Man Page]'
complete -c ecparam -o list_curves --description 'If this options is specified ecparam will pri... [See Man Page]'
complete -c ecparam -o conv_form --description 'This specifies how the points on the elliptic... [See Man Page]'
complete -c ecparam -o param_enc --description 'This specifies how the elliptic curve paramet... [See Man Page]'
complete -c ecparam -o no_seed --description 'This option inhibits that the \'seed\' for the ... [See Man Page]'
complete -c ecparam -o genkey --description 'This option will generate a \\s-1EC\\s0 private... [See Man Page]'
complete -c ecparam -o rand --description 'a file or files containing random data used t... [See Man Page]'

