# ecpg: Deroffing man parser
# Autogenerated from man pages
complete -c ecpg -s c --description 'Automatically generate certain C code from SQ... [See Man Page]'
complete -c ecpg -s C --description 'Set a compatibility mode'
complete -c ecpg -s D --description 'Define a C preprocessor symbol'
complete -c ecpg -s i --description 'Parse system include files as well'
complete -c ecpg -s I --description 'Specify an additional include path, used to f... [See Man Page]'
complete -c ecpg -s o --description 'Specifies that ecpg should write all its outp... [See Man Page]'
complete -c ecpg -s t --description 'Turn on autocommit of transactions'
complete -c ecpg -s v --description 'Print additional information including the ve... [See Man Page]'
complete -c ecpg -l version --description 'Print the ecpg version and exit'
complete -c ecpg -l help --description 'Show help about ecpg command line arguments, ... [See Man Page]'
complete -c ecpg -s r
complete -c ecpg -o 'I/usr/local/pgsql/include).'
complete -c ecpg -o L/usr/local/pgsql/lib -o 'lecpg.'

