# epmd: Deroffing man parser
# Autogenerated from man pages
complete -c epmd -o address --description 'Let this instance of epmd listen only on the ... [See Man Page]'
complete -c epmd -o port --description 'Let this instance of epmd listen to another T... [See Man Page]'
complete -c epmd -s d -o debug: --description 'Enable debug output'
complete -c epmd -o daemon: --description 'Start epmd detached from the controlling term... [See Man Page]'
complete -c epmd -o relaxed_command_check: --description 'Start the epmd program with relaxed command c... [See Man Page]'
complete -c epmd -o packet_timeout --description 'Set the number of seconds a connection can be... [See Man Page]'
complete -c epmd -o delay_accept --description 'To simulate a busy server you can insert a de... [See Man Page]'
complete -c epmd -o delay_write --description 'Also a simulation of a busy server'
complete -c epmd -o names: --description 'List names registered with the currently runn... [See Man Page]'
complete -c epmd -o kill: --description 'Kill the currently running epmd'
complete -c epmd -o stop --description 'Forcibly unregister a live node from epmd\'s d... [See Man Page]'

