# erl_call: Deroffing man parser
# Autogenerated from man pages
complete -c erl_call -s a --description '(optional): Applies the specified function an... [See Man Page]'
complete -c erl_call -s c --description '(optional): Use this option to specify a cert... [See Man Page]'
complete -c erl_call -o d: --description '(optional): Debug mode'
complete -c erl_call -o e: --description '(optional): Reads a sequence of Erlang expres... [See Man Page]'
complete -c erl_call -s h --description '(optional): Specifies the name of the hidden ... [See Man Page]'
complete -c erl_call -o m: --description '(optional): Reads an Erlang module from stdin... [See Man Page]'
complete -c erl_call -s n --description '(one of -n, -name, -sname is required): Has t... [See Man Page]'
complete -c erl_call -o name --description '(one of -n, -name, -sname is required): Node ... [See Man Page]'
complete -c erl_call -o q: --description '(optional): Halts the Erlang node specified w... [See Man Page]'
complete -c erl_call -o r: --description '(optional): Generates a random name of the hi... [See Man Page]'
complete -c erl_call -o s: --description '(optional): Starts a distributed Erlang node ... [See Man Page]'
complete -c erl_call -o sname --description '(one of -n, -name, -sname is required): Node ... [See Man Page]'
complete -c erl_call -o v: --description '(optional): Prints a lot of verbose informati... [See Man Page]'
complete -c erl_call -s x --description '(optional): Specifies another name of the Erl... [See Man Page]'
complete -c erl_call -o 'module(lolita).'
complete -c erl_call -o 'compile(export_all).' --description 'start() ->         P = processes(),         F... [See Man Page]'

