# erlsrv: Deroffing man parser
# Autogenerated from man pages
complete -c erlsrv -o 'st[opaction]' --description 'Defines the StopAction, the command given to ... [See Man Page]'
complete -c erlsrv -o 'on[fail]' --description 'Specifies the action to take when the Erlang ... [See Man Page]'
complete -c erlsrv -o 'm[achine]' --description 'The complete path to the Erlang emulator, nev... [See Man Page]'
complete -c erlsrv -o 'e[nv]' --description 'Edits the environment block for the service'
complete -c erlsrv -o 'w[orkdir]' --description 'The initial working directory of the Erlang e... [See Man Page]'
complete -c erlsrv -o 'p[riority]' --description 'The priority of the Erlang emulator'
complete -c erlsrv -o 'd[ebugtype]' --description 'Specifies where shell output should be sent, ... [See Man Page]'
complete -c erlsrv -o 'ar[gs]' --description 'Additional arguments to the Erlang emulator, ... [See Man Page]'
complete -c erlsrv -o 'i[nternalservicename]' --description 'Only allowed for add'
complete -c erlsrv -o 'c[omment]' --description 'Specifies a textual comment describing the se... [See Man Page]'

