# escript: Deroffing man parser
# Autogenerated from man pages
complete -c escript -o 'include_lib(' --description 'to include the record definitions for the rec... [See Man Page]'
complete -c escript -o 'mode(compile).' --description 'Execution of interpreted code is slower than ... [See Man Page]'
complete -c escript -o c: --description 'Compile the escript regardless of the value o... [See Man Page]'
complete -c escript -o d: --description 'Debug the escript'
complete -c escript -o i: --description 'Interpret the escript regardless of the value... [See Man Page]'
complete -c escript -o s: --description 'Only perform a syntactic and semantic check o... [See Man Page]'
complete -c escript -o n: --description 'Compile the escript using the +native flag'

