# fc-cache: Type1
# Autogenerated from man pages
complete -c fc-cache -s f --description 'Force re-generation of apparently up-to-date ... [See Man Page]'
complete -c fc-cache -s r --description 'Erase all existing cache files and rescan'
complete -c fc-cache -s s --description 'Only scan system-wide directories, omitting t... [See Man Page]'
complete -c fc-cache -s v --description 'Display status information while busy'
complete -c fc-cache -s h --description 'Show summary of options'
complete -c fc-cache -s V --description 'Show version of the program and exit'

