# fc-cat: Type1
# Autogenerated from man pages
complete -c fc-cat -s r --description 'Recurse into subdirectories'
complete -c fc-cat -s v --description 'Be verbose'
complete -c fc-cat -s h --description 'Show summary of options'

