# fc-list: Type1
# Autogenerated from man pages
complete -c fc-list -s v --description 'Print verbose output of the whole font patter... [See Man Page]'
complete -c fc-list -s f --description 'Format output according to the format specifi... [See Man Page]'
complete -c fc-list -s V --description 'Show version of the program and exit'
complete -c fc-list -s h --description 'Show summary of options'

