# fc-match: Type1
# Autogenerated from man pages
complete -c fc-match -s a --description 'Displays sorted list of best matching fonts, ... [See Man Page]'
complete -c fc-match -s s --description 'Displays sorted list of best matching fonts'
complete -c fc-match -s v --description 'Print verbose output of the whole font patter... [See Man Page]'
complete -c fc-match -s f --description 'Format output according to the format specifi... [See Man Page]'
complete -c fc-match -s V --description 'Show version of the program and exit'
complete -c fc-match -s h --description 'Show summary of options'

