# fc-pattern: Type1
# Autogenerated from man pages
complete -c fc-pattern -s c --description 'Perform config substitution on pattern'
complete -c fc-pattern -s d --description 'Perform default substitution on pattern'
complete -c fc-pattern -s f --description 'Format output according to the format specifi... [See Man Page]'
complete -c fc-pattern -s V --description 'Show version of the program and exit'
complete -c fc-pattern -s h --description 'Show summary of options'

