# fc-query: Type1
# Autogenerated from man pages
complete -c fc-query -s i --description 'Only query face indexed index of each file'
complete -c fc-query -s f --description 'Format output according to the format specifi... [See Man Page]'
complete -c fc-query -s V --description 'Show version of the program and exit'
complete -c fc-query -s h --description 'Show summary of options'

