# fc-scan: Type1
# Autogenerated from man pages
complete -c fc-scan -s f --description 'Format output according to the format specifi... [See Man Page]'
complete -c fc-scan -s V --description 'Show version of the program and exit'
complete -c fc-scan -s h --description 'Show summary of options'

