# fc-validate: Type1
# Autogenerated from man pages
complete -c fc-validate -s i --description 'Only query face indexed index of each file'
complete -c fc-validate -s l --description 'Set lang as a language instead of current loc... [See Man Page]'
complete -c fc-validate -s v --description 'Show more detailed information'
complete -c fc-validate -s V --description 'Show version of the program and exit'
complete -c fc-validate -s h --description 'Show summary of options'

