# fdp: Deroffing man parser
# Autogenerated from man pages
complete -c fdp -o Tps
complete -c fdp -o Tsvg -o Tsvgz
complete -c fdp -o Tfig
complete -c fdp -o Tmif
complete -c fdp -o Thpgl -o Tpcl
complete -c fdp -o Tpng -o Tgif
complete -c fdp -o Tdia
complete -c fdp -o Timap --description 'that has a non-null "href" attribute'
complete -c fdp -o Tcmapx --description 'Additional less common or more special-purpos... [See Man Page]'
complete -c fdp -s G
complete -c fdp -s N
complete -c fdp -s E --description 'Example: -Gsize="7,8" -Nshape=box -Efontsize=... [See Man Page]'
complete -c fdp -o lfile --description 'Usually these define custom shapes or styles'
complete -c fdp -o Tlang
complete -c fdp -o 'n[1' --description 'If set, neato assumes nodes have already been... [See Man Page]'
complete -c fdp -o Klayout
complete -c fdp -s O -s T
complete -c fdp -s P
complete -c fdp -s v
complete -c fdp -s V
complete -c fdp -s '?' --description EXAMPLES

