# fields: Deroffing man parser
# Autogenerated from man pages
complete -c fields -o config --description 'config file to use (default /etc/sqlrelay/sql... [See Man Page]'
complete -c fields -o id --description 'instance to use (as per config file)'

