# fonttosfnt: Deroffing man parser
# Autogenerated from man pages
complete -c fonttosfnt -s v --description 'Be verbose'
complete -c fonttosfnt -s c --description 'Do not crop glyphs'
complete -c fonttosfnt -s b --description 'Write byte-aligned glyph data'
complete -c fonttosfnt -s r --description 'Do not reencode fonts'
complete -c fonttosfnt -s g --description 'Set the type of scalable glyphs that we write... [See Man Page]'
complete -c fonttosfnt -s m --description 'Set the type of scalable metrics that we writ... [See Man Page]'

