# fslsfonts: Type1
# Autogenerated from man pages
complete -c fslsfonts -o server --description 'This option specifies the X font server to co... [See Man Page]'
complete -c fslsfonts -s l --description 'Lists some attributes of the font on one line... [See Man Page]'
complete -c fslsfonts -o ll --description 'Lists font properties in addition to -l outpu... [See Man Page]'
complete -c fslsfonts -o lll --description 'Supported for compatibility with xlsfonts, bu... [See Man Page]'
complete -c fslsfonts -s m --description 'This option indicates that long listings shou... [See Man Page]'
complete -c fslsfonts -s C --description 'This option indicates that listings should us... [See Man Page]'
complete -c fslsfonts -s 1 --description 'This option indicates that listings should us... [See Man Page]'
complete -c fslsfonts -s w --description 'This option specifies the width in characters... [See Man Page]'
complete -c fslsfonts -s n --description 'This option specifies the number of columns t... [See Man Page]'

