# fstobdf: Deroffing man parser
# Autogenerated from man pages
complete -c fstobdf -o server --description 'This option specifies the server from which t... [See Man Page]'
complete -c fstobdf -o fn --description 'This option specifies the font for which a BD... [See Man Page]'

