# gc: Deroffing man parser
# Autogenerated from man pages
complete -c gc -s n --description 'Count nodes'
complete -c gc -s e --description 'Count edges'
complete -c gc -s c --description 'Count connected components'
complete -c gc -s C --description 'Count clusters'
complete -c gc -s a --description 'Count all'
complete -c gc -s r --description 'Recursively analyze subgraphs'
complete -c gc -s s --description 'Print no output'
complete -c gc -s D --description 'Only analyze directed graphs'
complete -c gc -s U --description 'Only analyze undirected graphs'
complete -c gc -o encC
complete -c gc -s '?' --description 'Print usage information'
complete -c gc -s E --description 'option was used, and a graph of the wrong typ... [See Man Page]'

