# gccmakedep: Deroffing man parser
# Autogenerated from man pages
complete -c gccmakedep -s a --description 'Append the dependencies to the file instead o... [See Man Page]'
complete -c gccmakedep -s f --description Filename
complete -c gccmakedep -s s --description 'Starting string delimiter'
complete -c gccmakedep -s D --description and
complete -c gccmakedep -s U --description 'options to define and undefine symbols and'
complete -c gccmakedep -s I --description 'to set the include path'
complete -c gccmakedep -o f- --description 'sends the output to standard output instead o... [See Man Page]'

