# gendsa: Type1
# Autogenerated from man pages
complete -c gendsa -o des -o des3 -o idea --description 'These options encrypt the private key with th... [See Man Page]'
complete -c gendsa -o rand --description 'a file or files containing random data used t... [See Man Page]'
complete -c gendsa -o engine --description 'specifying an engine (by it\'s unique id strin... [See Man Page]'

