# genrsa: Type1
# Autogenerated from man pages
complete -c genrsa -o out --description 'the output filename'
complete -c genrsa -o passout --description 'the output file password source'
complete -c genrsa -o des -o des3 -o idea --description 'These options encrypt the private key with th... [See Man Page]'
complete -c genrsa -o F4 -s 3 --description 'the public exponent to use, either 65537 or 3... [See Man Page]'
complete -c genrsa -o rand --description 'a file or files containing random data used t... [See Man Page]'
complete -c genrsa -o engine --description 'specifying an engine (by it\'s unique id strin... [See Man Page]'

