# git-log: Deroffing man parser
# Autogenerated from man pages
complete -c git-log -o '<n>' --description 'Limits the number of commits to show'
complete -c git-log -l no-walk --description 'Only show the given revs, but do not traverse... [See Man Page]'

