# git-check-ignore: Deroffing man parser
# Autogenerated from man pages
complete -c git-check-ignore -s q -l quiet --description 'Don\\(cqt output anything, just set exit statu... [See Man Page]'
complete -c git-check-ignore -s v -l verbose --description 'Also output details about the matching patter... [See Man Page]'
complete -c git-check-ignore -l stdin --description 'Read file names from stdin instead of from th... [See Man Page]'
complete -c git-check-ignore -s z --description 'The output format is modified to be machine-p... [See Man Page]'

