# git-fast-import: Deroffing man parser
# Autogenerated from man pages
complete -c git-fast-import -l relative-marks --description 'After specifying --relative-marks the paths s... [See Man Page]'
complete -c git-fast-import -l no-relative-marks --description 'Negates a previous --relative-marks'

