# gitk: Deroffing man parser
# Autogenerated from man pages
complete -c gitk -s n -l max-count --description 'Limits the number of commits to show'
complete -c gitk -l since --description 'Show commits more recent than a specific date... [See Man Page]'
complete -c gitk -l until --description 'Show commits older than a specific date'
complete -c gitk -l all --description 'Show all branches'
complete -c gitk -l merge --description 'After an attempt to merge stops with conflict... [See Man Page]'
complete -c gitk -l argscmd --description 'Command to be run each time gitk has to deter... [See Man Page]'
complete -c gitk -l select-commit --description 'Automatically select the specified commit aft... [See Man Page]'

