# gitremote-helpers: Deroffing man parser
# Autogenerated from man pages
complete -c gitremote-helpers -l export-marks --description 'in git-fast-export(1)'
complete -c gitremote-helpers -l import-marks --description 'in git-fast-export(1)'

