# gml2gv: Deroffing man parser
# Autogenerated from man pages
complete -c gml2gv -s v --description 'Turns on verbose mode'
complete -c gml2gv -s '?' --description 'Prints usage information and exits'
complete -c gml2gv -s g --description 'The string gname is used as the name of the g... [See Man Page]'
complete -c gml2gv -s o --description 'Prints output to the file outfile'

