# gsed: Deroffing man parser
# Autogenerated from man pages
complete -c gsed -l help --description 'display this help and exit'
complete -c gsed -s n -l quiet -l silent --description 'suppress automatic printing of pattern space'
complete -c gsed -s e -l expression --description 'add the script to the commands to be executed'
complete -c gsed -s f -l file --description 'add the contents of script-file to the comman... [See Man Page]'
complete -c gsed -l follow-symlinks --description 'follow symlinks when processing in place'
complete -c gsed -o 'i[SUFFIX]' -l 'in-place[' --description 'edit files in place (makes backup if SUFFIX s... [See Man Page]'
complete -c gsed -s l -l line-length --description 'specify the desired line-wrap length for the ... [See Man Page]'
complete -c gsed -l posix --description 'disable all GNU extensions'
complete -c gsed -s r -l regexp-extended --description 'use extended regular expressions in the scrip... [See Man Page]'
complete -c gsed -s s -l separate --description 'consider files as separate rather than as a s... [See Man Page]'
complete -c gsed -s u -l unbuffered --description 'load minimal amounts of data from the input f... [See Man Page]'
complete -c gsed -s z -l null-data --description 'separate lines by NUL characters'
complete -c gsed -l version --description 'output version information and exit'

