# gtf: Deroffing man parser
# Autogenerated from man pages
complete -c gtf -s v -l verbose --description 'Enable verbose printouts  This shows a trace ... [See Man Page]'
complete -c gtf -s x -l xorgmode --description 'Print the mode parameters as Xorg-style mode ... [See Man Page]'
complete -c gtf -s f -l fbset --description 'Print the mode parameters in a format suitabl... [See Man Page]'

