# gv2gml: Deroffing man parser
# Autogenerated from man pages
complete -c gv2gml -s v --description 'Turns on verbose mode'
complete -c gv2gml -s '?' --description 'Prints usage information and exits'
complete -c gv2gml -s g --description 'The string gname is used as the name of the g... [See Man Page]'
complete -c gv2gml -s o --description 'Prints output to the file outfile'

