# gv2gxl: Deroffing man parser
# Autogenerated from man pages
complete -c gv2gxl -s g --description 'The command name and input file extensions ar... [See Man Page]'
complete -c gv2gxl -s d --description 'The command name and input file extensions ar... [See Man Page]'
complete -c gv2gxl -s '?' --description 'Prints usage information and exits'
complete -c gv2gxl -s o --description 'If specified, the output will be written into... [See Man Page]'

