# gvmap: Deroffing man parser
# Autogenerated from man pages
complete -c gvmap -s K --description 'specifies which program should be use for the... [See Man Page]'
complete -c gvmap -s T --description 'specifies the final output format'
complete -c gvmap -s N --description 'specifies the setting of a default node attri... [See Man Page]'
complete -c gvmap -s G --description 'specifies the setting of a graph attribute du... [See Man Page]'
complete -c gvmap -s E --description 'specifies the setting of a default edge attri... [See Man Page]'
complete -c gvmap -s n --description 'specifies the setting of a default node attri... [See Man Page]'
complete -c gvmap -s A --description 'specifies a flag to be passed to gvmap'
complete -c gvmap -s V --description 'Print version information and exit'

