# gvpack: Deroffing man parser
# Autogenerated from man pages
complete -c gvpack -s g --description 'Combines the graphs at the graph level'
complete -c gvpack -o 'array[_flags][n]' --description 'Combines the graphs at the graph level, placi... [See Man Page]'
complete -c gvpack -s G --description 'Specifies attributes to be added to the resul... [See Man Page]'
complete -c gvpack -s m --description 'Packs the graphs allowing a margin of output ... [See Man Page]'
complete -c gvpack -s n --description 'Combines the graphs at the node level'
complete -c gvpack -s o --description 'Prints output to the file output'
complete -c gvpack -s u --description 'Don\'t pack the graphs'
complete -c gvpack -s v --description 'Verbose mode'
complete -c gvpack -s '?' --description 'Prints usage information and exit'

