# gvpr: Deroffing man parser
# Autogenerated from man pages
complete -c gvpr -s a --description 'The string args is split into whitespace\\(hys... [See Man Page]'
complete -c gvpr -s c --description 'Use the source graph as the output graph'
complete -c gvpr -s i --description 'Derive the node\\(hyinduced subgraph extension... [See Man Page]'
complete -c gvpr -s o --description 'Causes the output stream to be written to the... [See Man Page]'
complete -c gvpr -s f --description 'Use the contents of the specified file as the... [See Man Page]'
complete -c gvpr -s q --description 'Turns off warning messages'
complete -c gvpr -s n --description 'Turns off graph read-ahead'
complete -c gvpr -s V --description 'Causes the program to print version informati... [See Man Page]'
complete -c gvpr -s '?' --description 'Causes the program to print usage information... [See Man Page]'

