# gxl2gv: Deroffing man parser
# Autogenerated from man pages
complete -c gxl2gv -s g --description 'The command name and input file extensions ar... [See Man Page]'
complete -c gxl2gv -s d --description 'The command name and input file extensions ar... [See Man Page]'
complete -c gxl2gv -s '?' --description 'Prints usage information and exits'
complete -c gxl2gv -s o --description 'If specified, the output will be written into... [See Man Page]'

