# hg: Deroffing man parser
# Autogenerated from man pages
complete -c hg -s R -l repository
complete -c hg -l cwd
complete -c hg -s y -l noninteractive
complete -c hg -s q -l quiet
complete -c hg -s v -l verbose
complete -c hg -l config
complete -c hg -l debug
complete -c hg -l debugger
complete -c hg -l encoding
complete -c hg -l encodingmode
complete -c hg -l traceback
complete -c hg -l time
complete -c hg -l profile
complete -c hg -l version
complete -c hg -s h -l help
complete -c hg -l hidden
complete -c hg -s I -l include
complete -c hg -s X -l exclude
complete -c hg -s S -l subrepos
complete -c hg -s n -l dry-run
complete -c hg -s s -l similarity
complete -c hg -s r -l rev
complete -c hg -l follow
complete -c hg -l no-follow
complete -c hg -s a -l text
complete -c hg -s u -l user
complete -c hg -s f -l file
complete -c hg -s d -l date
complete -c hg -l number
complete -c hg -s c -l changeset
complete -c hg -s l -l line-number
complete -c hg -s w -l ignore-all-space
complete -c hg -s b -l ignore-space-change
complete -c hg -s B -l ignore-blank-lines
complete -c hg -l no-decode
complete -c hg -s p -l prefix
complete -c hg -s t -l type
complete -c hg -l merge
complete -c hg -l parent
complete -c hg -l tool
complete -c hg -s m -l message
complete -c hg -l logfile
complete -c hg -l reset
complete -c hg -s g -l good
complete -c hg -l bad
complete -c hg -l skip
complete -c hg -s e -l extend
complete -c hg -l command
complete -c hg -s U -l noupdate
complete -c hg -l force
complete -c hg -l delete
complete -c hg -l rename
complete -c hg -s i -l inactive
complete -c hg -s C -l clean
complete -c hg -l active
complete -c hg -l closed
complete -c hg -o a/--all -l base
complete -c hg -l branch
complete -c hg -l all
complete -c hg -l ssh
complete -c hg -l remotecmd
complete -c hg -l insecure
complete -c hg -s o -l output
complete -c hg -l decode
complete -c hg -l pull --description 'tag will include the tagged changeset but not... [See Man Page]'
complete -c hg -o U/--noupdate
complete -c hg -l updaterev
complete -c hg -l uncompressed
complete -c hg -s A -l addremove
complete -c hg -l close-branch
complete -c hg -l amend
complete -c hg -l after
complete -c hg -l change
complete -c hg -l git
complete -c hg -l nodates
complete -c hg -l show-function
complete -c hg -l reverse
complete -c hg -l unified
complete -c hg -l stat
complete -c hg -l switch-parent
complete -c hg -l continue
complete -c hg -l edit
complete -c hg -l log
complete -c hg -s D -l currentdate
complete -c hg -l currentuser
complete -c hg -s 0 -l print0
complete -c hg -l ignore-case
complete -c hg -l files-with-matches
complete -c hg -l topo
complete -c hg -l style
complete -c hg -l template
complete -c hg -l extension
complete -c hg -s k -l keyword
complete -c hg -l num
complete -c hg -l id
complete -c hg -l tags
complete -c hg -l bookmarks
complete -c hg -l no-commit
complete -c hg -l strip
complete -c hg -l bypass
complete -c hg -l exact
complete -c hg -l import-branch
complete -c hg -l newest-first
complete -c hg -l bundle
complete -c hg -l patch
complete -c hg -l limit
complete -c hg -s M -l no-merges
complete -c hg -s G -l graph
complete -c hg -l fullpath
complete -c hg -l follow-first
complete -c hg -l copies
complete -c hg -l removed
complete -c hg -l only-merges
complete -c hg -l only-branch
complete -c hg -s P -l prune
complete -c hg -l preview
complete -c hg -l public
complete -c hg -l draft
complete -c hg -l secret
complete -c hg -l update
complete -c hg -l bookmark
complete -c hg -l new-branch
complete -c hg -o A/--after --description 'been deleted, -f/--force can be used to force... [See Man Page]'
complete -c hg -o Af --description 'T}	T{ R T}	T{ R T}	T{ R T}	T{ R T} _ Note tha... [See Man Page]'
complete -c hg -l list
complete -c hg -l mark
complete -c hg -l unmark
complete -c hg -l no-status
complete -c hg -l no-backup
complete -c hg -l accesslog
complete -c hg -l daemon
complete -c hg -l daemon-pipefds
complete -c hg -s E -l errorlog
complete -c hg -l port
complete -c hg -l address
complete -c hg -l name
complete -c hg -l web-conf
complete -c hg -l webdir-conf
complete -c hg -l pid-file
complete -c hg -l stdio
complete -c hg -l cmdserver
complete -c hg -l templates
complete -c hg -s 6 -l ipv6
complete -c hg -l certificate
complete -c hg -l untrusted
complete -c hg -o c/--clean -o i/--ignored -o C/--copies -o A/--all --description 'Unless options described with "show only '
complete -c hg -l modified
complete -c hg -l added
complete -c hg -l deleted
complete -c hg -l unknown
complete -c hg -l ignored
complete -c hg -l remote
complete -c hg -o f/--force --description changeset
complete -c hg -l local
complete -c hg -l remove
complete -c hg -l check
complete -c hg -o DAYS
complete -c hg -s 2
complete -c hg -s '>'
complete -c hg -o S/--subrepos
complete -c hg -l changesets
complete -c hg -l dateformat
complete -c hg -l sort
complete -c hg -l diffstat
complete -c hg -l aliases
complete -c hg -l branchsort
complete -c hg -l datesort
complete -c hg -l 'branchsort.'
complete -c hg -l sourcesort
complete -c hg -l authors
complete -c hg -l source-type
complete -c hg -l dest-type
complete -c hg -l authormap
complete -c hg -l filemap
complete -c hg -l splicemap
complete -c hg -l branchmap
complete -c hg -l program
complete -c hg -l option
complete -c hg -l force-editor
complete -c hg -l key
complete -c hg -l commands
complete -c hg -l keep
complete -c hg -l abort
complete -c hg -l outgoing
complete -c hg -l idle-timeout
complete -c hg -l default
complete -c hg -l rcfile
complete -c hg -l ignore
complete -c hg -l large --description '$ dd if=/dev/urandom of=randomdata count=2000... [See Man Page]'
complete -c hg -l lfsize --description '[largefiles] minsize = 2'
complete -c hg -l size
complete -c hg -l to-normal
complete -c hg -s 1 -l last
complete -c hg -l summary
complete -c hg -l patches
complete -c hg -l applied
complete -c hg -l keep-changes
complete -c hg -l none
complete -c hg -l existing
complete -c hg -l push
complete -c hg -o c/--create-repo --description 'repository for patches (qinit -c may also be ... [See Man Page]'
complete -c hg -l create-repo
complete -c hg -o X/--exclude --description 'only changes to matching files to the new pat... [See Man Page]'
complete -c hg -o u/--user -o d/--date --description 'date, respectively'
complete -c hg -o e/--edit -o m/--message -o l/--logfile --description 'well as the commit message'
complete -c hg -l move
complete -c hg -l create
complete -c hg -l purge
complete -c hg -l short
complete -c hg -l copy
complete -c hg -l empty
complete -c hg -l 'pop)' --description 'guarded patches'
complete -c hg -l series
complete -c hg -l pop
complete -c hg -l reapply
complete -c hg -l missing
complete -c hg -l first
complete -c hg -l backup
complete -c hg -l nobackup
complete -c hg -o a/--attach -o i/--inline -l body
complete -c hg -l plain
complete -c hg -l bundlename
complete -c hg -l intro
complete -c hg -l attach
complete -c hg -l inline
complete -c hg -l bcc
complete -c hg -l cc
complete -c hg -l confirm
complete -c hg -l desc
complete -c hg -l from
complete -c hg -l test
complete -c hg -l mbox
complete -c hg -l reply-to
complete -c hg -l subject
complete -c hg -l in-reply-to
complete -c hg -l flag
complete -c hg -l to
complete -c hg -l abort-on-err
complete -c hg -l print
complete -c hg -o s: --description 'specify any changeset in the source branch, a... [See Man Page]'
complete -c hg -l source
complete -c hg -l dest
complete -c hg -l collapse
complete -c hg -l keepbranches
complete -c hg -l detach
complete -c hg -l all/-a --description 'transplanted, otherwise you will be prompted ... [See Man Page]'
complete -c hg -l 'continue/-c.'
complete -c hg -l filter

