# httxt2dbm: Type1
# Autogenerated from man pages
complete -c httxt2dbm -s v --description 'More verbose output'
complete -c httxt2dbm -s f --description 'Specify the DBM type to be used for the outpu... [See Man Page]'
complete -c httxt2dbm -s i --description 'Input file from which the dbm is to be create... [See Man Page]'

