# iceauth: Deroffing man parser
# Autogenerated from man pages
complete -c iceauth -s f --description '             the file currently in use by the... [See Man Page]'
complete -c iceauth -s v
complete -c iceauth -s q
complete -c iceauth -s i
complete -c iceauth -s b
complete -c iceauth -s u

