# ico: Deroffing man parser
# Autogenerated from man pages
complete -c ico -s r --description 'Display on the root window instead of creatin... [See Man Page]'
complete -c ico -s d --description 'Specify a bit pattern for drawing dashed line... [See Man Page]'
complete -c ico -s i --description 'Use inverted colors for wire frames'
complete -c ico -o dbl --description 'Use double buffering on the display'
complete -c ico -o faces --description 'Draw filled faces instead of wire frames'
complete -c ico -o noedges --description 'Don\'t draw the wire frames'
complete -c ico -o sleep --description 'Sleep n seconds between each move of the obje... [See Man Page]'
complete -c ico -o obj --description 'Specify what object to draw'
complete -c ico -o objhelp --description 'Print out a list of the available objects, al... [See Man Page]'
complete -c ico -o colors --description 'Specify what colors should be used to draw th... [See Man Page]'

