# kgetcred: Darwin man parser
# Autogenerated from man pages
complete -c kgetcred -l canonicalize --description 'requests that the KDC canonicalize the princi... [See Man Page]'
complete -c kgetcred -s c --description 'the credential cache to use'
complete -c kgetcred -s e --description 'encryption type to use'
complete -c kgetcred -l no-transit-check --description 'requests that the KDC doesn\'t do transit chec... [See Man Page]'
complete -c kgetcred -l version
complete -c kgetcred -l help

