# klist: Darwin man parser
# Autogenerated from man pages
complete -c klist -s c --description 'credential cache to list'
complete -c klist -s s --description 'Test for there being an active and valid TGT ... [See Man Page]'
complete -c klist -s T --description 'display AFS tokens'
complete -c klist -s 5 --description 'display v5 cred cache (this is the default)'
complete -c klist -s f --description 'Include ticket flags in short form, each char... [See Man Page]'
complete -c klist -s v --description 'Verbose output'
complete -c klist -s l --description 'List the credential caches for the current us... [See Man Page]'

