# koi8rxterm: Deroffing man parser
# Autogenerated from man pages
complete -c koi8rxterm -o class --description and
complete -c koi8rxterm -o k8 --description 'options should not be specified because they ... [See Man Page]'

