# lefty: Deroffing man parser
# Autogenerated from man pages
complete -c lefty -s x --description 'Instructs the editor to exit after processing... [See Man Page]'
complete -c lefty -s e --description '<expression> is parsed and executed'
complete -c lefty -o el --description 'Set error reporting level'
complete -c lefty -o sd --description 'Specifies how much of the stack to show, when... [See Man Page]'
complete -c lefty -o sb --description 'Specifies how much of each function in the st... [See Man Page]'
complete -c lefty -o df --description 'Sets the default font'
complete -c lefty -o ps --description 'Specifies a default file name for postscript ... [See Man Page]'
complete -c lefty -s V --description 'Prints the version'

