# listres: Deroffing man parser
# Autogenerated from man pages
complete -c listres -o all --description 'This option indicates that listres should pri... [See Man Page]'
complete -c listres -o nosuper --description 'This option indicates that resources that are... [See Man Page]'
complete -c listres -o variable --description 'This option indicates that widgets should be ... [See Man Page]'
complete -c listres -o top --description 'This option specifies the name of the widget ... [See Man Page]'
complete -c listres -o format --description 'This option specifies the printf-style format... [See Man Page]'

