# lndir: Deroffing man parser
# Autogenerated from man pages
complete -c lndir -o silent --description 'Normally lndir outputs the name of each subdi... [See Man Page]'
complete -c lndir -o ignorelinks --description 'Causes the program to not treat symbolic link... [See Man Page]'
complete -c lndir -o withrevinfo --description 'Causes any source control manager subdirector... [See Man Page]'

