# lzmadec: Deroffing man parser
# Autogenerated from man pages
complete -c lzmadec -s d -l decompress -l uncompress --description 'Ignored for  xz (1) compatibility'
complete -c lzmadec -s k -l keep --description 'Ignored for  xz (1) compatibility'
complete -c lzmadec -s c -l stdout -l to-stdout --description 'Ignored for  xz (1) compatibility'
complete -c lzmadec -s q -l quiet --description 'Specifying this once does nothing since  xzde... [See Man Page]'
complete -c lzmadec -s Q -l no-warn --description 'Ignored for  xz (1) compatibility'
complete -c lzmadec -s h -l help --description 'Display a help message and exit successfully'
complete -c lzmadec -s V -l version --description 'Display the version number of xzdec and liblz... [See Man Page]'

