# makedepend: Deroffing man parser
# Autogenerated from man pages
complete -c makedepend -o Dname -o Dname --description Define
complete -c makedepend -o Iincludedir --description 'Include directory'
complete -c makedepend -o Yincludedir --description 'Replace all of the standard include directori... [See Man Page]'
complete -c makedepend -s a --description 'Append the dependencies to the end of the fil... [See Man Page]'
complete -c makedepend -o fmakefile --description Filename
complete -c makedepend -o include --description 'Process file as input, and include all the re... [See Man Page]'
complete -c makedepend -o oobjsuffix --description 'Object file suffix'
complete -c makedepend -o pobjprefix --description 'Object file prefix'
complete -c makedepend -o sstring --description 'Starting string delimiter'
complete -c makedepend -o wwidth --description 'Line width'
complete -c makedepend -s v --description 'Verbose operation'
complete -c makedepend -s m --description 'Warn about multiple inclusion'
complete -c makedepend -s f --description option
complete -c makedepend -s s --description 'option, as a delimiter for the dependency out... [See Man Page]'
complete -c makedepend -o 'o.b' --description 'or ``:obj\'\' with'
complete -c makedepend -o o:obj --description 'and so forth'
complete -c makedepend -s I --description and
complete -c makedepend -s D --description 'options; and that most files in a single dire... [See Man Page]'

