# md5: Darwin man parser
# Autogenerated from man pages
complete -c md5 -s s --description 'Print a checksum of the given'
complete -c md5 -s p --description 'Echo stdin to stdout and append the checksum ... [See Man Page]'
complete -c md5 -s q --description 'Quiet mode - only the checksum is printed out... [See Man Page]'
complete -c md5 -s r --description 'Reverses the format of the output'
complete -c md5 -s t --description 'Run a built-in time trial'
complete -c md5 -s x --description 'Run a built-in test script'

