# migcom: Deroffing man parser
# Autogenerated from man pages
complete -c migcom -o q/-Q --description 'Omit /  emit warning messages'
complete -c migcom -o v/-V --description 'Verbose mode ( on /  off ) will summarize typ... [See Man Page]'
complete -c migcom -o l/-L --description 'Controls (  off / on ) whether or not generat... [See Man Page]'
complete -c migcom -o k/-K --description 'Controls (  on / off ) whether generated code... [See Man Page]'
complete -c migcom -o s/-S --description 'Controls ( on /  off ) whether generated serv... [See Man Page]'
complete -c migcom -s i --description 'Specify User file prefix'
complete -c migcom -o user --description 'Specify name of user-side RPC generated sourc... [See Man Page]'
complete -c migcom -o server --description 'Specify name of server-side RPC generated sou... [See Man Page]'
complete -c migcom -o header --description 'Specify name of user-side generated header fi... [See Man Page]'
complete -c migcom -o sheader --description 'Specify name of server-side generated header ... [See Man Page]'
complete -c migcom -o iheader --description 'Specify internal header file name'
complete -c migcom -o dheader --description 'Specify defines generated header file'
complete -c migcom -o maxonstack --description 'Specify maximum size of message on stack'
complete -c migcom -o split --description 'Use split headers'

