# mkfontdir: Deroffing man parser
# Autogenerated from man pages
complete -c mkfontdir -s e --description 'Specify a directory containing encoding files... [See Man Page]'
complete -c mkfontdir -s n --description 'do not scan for fonts, do not write font dire... [See Man Page]'
complete -c mkfontdir -s p --description 'Specify a prefix that is prepended to the enc... [See Man Page]'
complete -c mkfontdir -s r --description 'Keep non-absolute encoding directories in the... [See Man Page]'
complete -c mkfontdir -s x --description 'Ignore fonts files of type R suffix '

