# mkfontscale: Deroffing man parser
# Autogenerated from man pages
complete -c mkfontscale -s b --description 'read bitmap fonts'
complete -c mkfontscale -s s --description 'ignore scalable fonts'
complete -c mkfontscale -s o --description 'send program output to R filename ; default i... [See Man Page]'
complete -c mkfontscale -s x --description 'exclude all files with the specified R suffix... [See Man Page]'
complete -c mkfontscale -s a --description 'add  encoding to the list of encodings search... [See Man Page]'
complete -c mkfontscale -s f --description 'set the fraction of characters that may be mi... [See Man Page]'
complete -c mkfontscale -s l --description 'Write  fonts'
complete -c mkfontscale -s e --description 'specifies a directory with encoding files'
complete -c mkfontscale -s p --description 'Specifies a prefix that is prepended to the e... [See Man Page]'
complete -c mkfontscale -s r --description 'Keep non-absolute encoding directories in the... [See Man Page]'
complete -c mkfontscale -s n --description 'do not scan for fonts, do not write font dire... [See Man Page]'

