# mm2gv: Deroffing man parser
# Autogenerated from man pages
complete -c mm2gv -s c --description 'This flag causes mm2gv to assign colors to th... [See Man Page]'
complete -c mm2gv -s l --description 'If set, mm2gv attaches a label to the graph i... [See Man Page]'
complete -c mm2gv -s u --description 'If specified, the graph is assumed to be undi... [See Man Page]'
complete -c mm2gv -s v --description 'This flag causes mm2gv to store the matrix va... [See Man Page]'
complete -c mm2gv -s o --description 'Prints output to the file outfile'

