# mysql_config_editor: Deroffing man parser
# Autogenerated from man pages
complete -c mysql_config_editor -l login-path --description 'option when you invoke a client program'
complete -c mysql_config_editor -l verbose --description 'to produce more information as mysql_config_e... [See Man Page]'
complete -c mysql_config_editor -l all
complete -c mysql_config_editor -l host
complete -c mysql_config_editor -l password
complete -c mysql_config_editor -l user
complete -c mysql_config_editor -l skip-warn --description option
complete -c mysql_config_editor -l help
complete -c mysql_config_editor -s '?'
complete -c mysql_config_editor -l 'debug['
complete -c mysql_config_editor -s '#'
complete -c mysql_config_editor -s h
complete -c mysql_config_editor -s G
complete -c mysql_config_editor -s p
complete -c mysql_config_editor -o 'ppass_val.' --description 'oc o 2'
complete -c mysql_config_editor -s u
complete -c mysql_config_editor -s v
complete -c mysql_config_editor -l version
complete -c mysql_config_editor -s V
complete -c mysql_config_editor -l warn
complete -c mysql_config_editor -s w

