# neato: Deroffing man parser
# Autogenerated from man pages
complete -c neato -o Tps
complete -c neato -o Tsvg -o Tsvgz
complete -c neato -o Tfig
complete -c neato -o Tmif
complete -c neato -o Thpgl -o Tpcl
complete -c neato -o Tpng -o Tgif
complete -c neato -o Tdia
complete -c neato -o Timap --description 'that has a non-null "href" attribute'
complete -c neato -o Tcmapx --description 'Additional less common or more special-purpos... [See Man Page]'
complete -c neato -s G
complete -c neato -s N
complete -c neato -s E --description 'Example: -Gsize="7,8" -Nshape=box -Efontsize=... [See Man Page]'
complete -c neato -o lfile --description 'Usually these define custom shapes or styles'
complete -c neato -o Tlang
complete -c neato -o 'n[1' --description 'If set, neato assumes nodes have already been... [See Man Page]'
complete -c neato -o Klayout
complete -c neato -s O -s T
complete -c neato -s P
complete -c neato -s v
complete -c neato -s V
complete -c neato -s '?' --description EXAMPLES

