# nop: Deroffing man parser
# Autogenerated from man pages
complete -c nop -s p --description 'Produce no output - just check the input for ... [See Man Page]'
complete -c nop -s '?' --description 'Print usage information'

