# notifyutil: Darwin man parser
# Autogenerated from man pages
complete -c notifyutil -s p --description 'Post a notification for'
complete -c notifyutil -s w --description 'Register for'
complete -c notifyutil -s '#' --description 'Register for'
complete -c notifyutil -s g --description 'Get state value for'
complete -c notifyutil -s s --description 'Set state value for'
complete -c notifyutil -l port --description 'Use mach port notifications for subsequent'
complete -c notifyutil -l file --description 'Use file descriptor notifications for subsequ... [See Man Page]'
complete -c notifyutil -l check --description 'Use shared memory notifications for subsequen... [See Man Page]'
complete -c notifyutil -l signal --description 'Use signal notifications for subsequent regis... [See Man Page]'
complete -c notifyutil -l dispatch --description 'Use dispatch for subsequent registrations'

