# oclock: Deroffing man parser
# Autogenerated from man pages
complete -c oclock -o fg --description 'choose a different color for the both hands a... [See Man Page]'
complete -c oclock -o bg --description 'choose a different color for the background'
complete -c oclock -o jewel --description 'choose a different color for the jewel on the... [See Man Page]'
complete -c oclock -o minute --description 'choose a different color for the minute hand ... [See Man Page]'
complete -c oclock -o hour --description 'choose a different color for the hour hand of... [See Man Page]'
complete -c oclock -o backing --description 'selects an appropriate level of backing store... [See Man Page]'
complete -c oclock -o geometry --description 'define the initial window geometry; see X(7)'
complete -c oclock -o display --description 'specify the display to use; see X(7)'
complete -c oclock -o bd --description 'choose a different color for the window borde... [See Man Page]'
complete -c oclock -o bw --description 'choose a different width for the window borde... [See Man Page]'
complete -c oclock -o shape --description 'causes the clock to use the Shape extension t... [See Man Page]'
complete -c oclock -o noshape --description 'causes the clock to not reshape itself and an... [See Man Page]'
complete -c oclock -o transparent --description 'causes the clock to consist only of the jewel... [See Man Page]'

