# osage: Deroffing man parser
# Autogenerated from man pages
complete -c osage -o Tps
complete -c osage -o Tsvg -o Tsvgz
complete -c osage -o Tfig
complete -c osage -o Tmif
complete -c osage -o Thpgl -o Tpcl
complete -c osage -o Tpng -o Tgif
complete -c osage -o Tdia
complete -c osage -o Timap --description 'that has a non-null "href" attribute'
complete -c osage -o Tcmapx --description 'Additional less common or more special-purpos... [See Man Page]'
complete -c osage -s G
complete -c osage -s N
complete -c osage -s E --description 'Example: -Gsize="7,8" -Nshape=box -Efontsize=... [See Man Page]'
complete -c osage -o lfile --description 'Usually these define custom shapes or styles'
complete -c osage -o Tlang
complete -c osage -s O -s T
complete -c osage -s v
complete -c osage -s V
complete -c osage -s '?' --description EXAMPLES

