# passwd: Type1
# Autogenerated from man pages
complete -c passwd -o crypt --description 'Use the crypt algorithm (default)'
complete -c passwd -s 1 --description 'Use the \\s-1MD5\\s0 based \\s-1BSD\\s0 password ... [See Man Page]'
complete -c passwd -o apr1 --description 'Use the apr1 algorithm (Apache variant of the... [See Man Page]'
complete -c passwd -o salt --description 'Use the specified salt'
complete -c passwd -o in --description 'Read passwords from file'
complete -c passwd -o stdin --description 'Read passwords from stdin'
complete -c passwd -o noverify --description 'Don\'t verify when reading a password from the... [See Man Page]'
complete -c passwd -o quiet --description 'Don\'t output warnings when passwords given at... [See Man Page]'

