# patchwork: Deroffing man parser
# Autogenerated from man pages
complete -c patchwork -o Tps
complete -c patchwork -o Tsvg -o Tsvgz
complete -c patchwork -o Tfig
complete -c patchwork -o Tmif
complete -c patchwork -o Thpgl -o Tpcl
complete -c patchwork -o Tpng -o Tgif
complete -c patchwork -o Tdia
complete -c patchwork -o Timap --description 'that has a non-null "href" attribute'
complete -c patchwork -o Tcmapx --description 'Additional less common or more special-purpos... [See Man Page]'
complete -c patchwork -s G
complete -c patchwork -s N
complete -c patchwork -s E --description 'Example: -Gsize="7,8" -Nshape=box -Efontsize=... [See Man Page]'
complete -c patchwork -o lfile --description 'Usually these define custom shapes or styles'
complete -c patchwork -o Tlang
complete -c patchwork -s O -s T
complete -c patchwork -s v
complete -c patchwork -s V
complete -c patchwork -s '?' --description EXAMPLES

