# pg_archivecleanup: Deroffing man parser
# Autogenerated from man pages
complete -c pg_archivecleanup -s d --description 'Print lots of debug logging output on stderr'
complete -c pg_archivecleanup -s n --description 'Print the names of the files that would have ... [See Man Page]'
complete -c pg_archivecleanup -s V -l version --description 'Print the pg_archivecleanup version and exit'
complete -c pg_archivecleanup -s x --description 'When using the program as a standalone utilit... [See Man Page]'
complete -c pg_archivecleanup -s '?' -l help --description 'Show help about pg_archivecleanup command lin... [See Man Page]'

