# pg_receivexlog: Deroffing man parser
# Autogenerated from man pages
complete -c pg_receivexlog -s D -l directory --description 'Directory to write the output to'
complete -c pg_receivexlog -s n -l no-loop --description 'Don\\*(Aqt loop on connection errors'
complete -c pg_receivexlog -s v -l verbose --description 'Enables verbose mode'
complete -c pg_receivexlog -s h -l host --description 'Specifies the host name of the machine on whi... [See Man Page]'
complete -c pg_receivexlog -s p -l port --description 'Specifies the TCP port or local Unix domain s... [See Man Page]'
complete -c pg_receivexlog -s s -l status-interval --description 'Specifies the number of seconds between statu... [See Man Page]'
complete -c pg_receivexlog -s U -l username --description 'User name to connect as'
complete -c pg_receivexlog -s w -l no-password --description 'Never issue a password prompt'
complete -c pg_receivexlog -s W -l password --description 'Force pg_receivexlog to prompt for a password... [See Man Page]'
complete -c pg_receivexlog -s V -l version --description 'Print the pg_receivexlog version and exit'
complete -c pg_receivexlog -s '?' -l help --description 'Show help about pg_receivexlog command line a... [See Man Page]'

