# pg_test_fsync: Deroffing man parser
# Autogenerated from man pages
complete -c pg_test_fsync -s f -l filename --description 'Specifies the file name to write test data in... [See Man Page]'
complete -c pg_test_fsync -s s -l secs-per-test --description 'Specifies the number of seconds for each test... [See Man Page]'
complete -c pg_test_fsync -s V -l version --description 'Print the pg_test_fsync version and exit'
complete -c pg_test_fsync -s '?' -l help --description 'Show help about pg_test_fsync command line ar... [See Man Page]'

