# pg_test_timing: Deroffing man parser
# Autogenerated from man pages
complete -c pg_test_timing -s d -l duration --description 'Specifies the test duration, in seconds'
complete -c pg_test_timing -s V -l version --description 'Print the pg_test_timing version and exit'
complete -c pg_test_timing -s '?' -l help --description 'Show help about pg_test_timing command line a... [See Man Page]'

