# pg_upgrade: Deroffing man parser
# Autogenerated from man pages
complete -c pg_upgrade -s b -l old-bindir --description 'the old cluster executable directory; environ... [See Man Page]'
complete -c pg_upgrade -s B -l new-bindir --description 'the new cluster executable directory; environ... [See Man Page]'
complete -c pg_upgrade -s c -l check --description 'check clusters only, don\\*(Aqt change any dat... [See Man Page]'
complete -c pg_upgrade -s d -l old-datadir --description 'the old cluster data directory; environment v... [See Man Page]'
complete -c pg_upgrade -s D -l new-datadir --description 'the new cluster data directory; environment v... [See Man Page]'
complete -c pg_upgrade -s k -l link --description 'use hard links instead of copying files to th... [See Man Page]'
complete -c pg_upgrade -s o -l old-options --description 'options to be passed directly to the old post... [See Man Page]'
complete -c pg_upgrade -s O -l new-options --description 'options to be passed directly to the new post... [See Man Page]'
complete -c pg_upgrade -s p -l old-port --description 'the old cluster port number; environment vari... [See Man Page]'
complete -c pg_upgrade -s P -l new-port --description 'the new cluster port number; environment vari... [See Man Page]'
complete -c pg_upgrade -s r -l retain --description 'retain SQL and log files even after successfu... [See Man Page]'
complete -c pg_upgrade -s u -l user --description 'cluster\\*(Aqs super user name; environment va... [See Man Page]'
complete -c pg_upgrade -s v -l verbose --description 'enable verbose internal logging'
complete -c pg_upgrade -s V -l version --description 'display version information, then exit'
complete -c pg_upgrade -s '?' -s h -l help --description 'show help, then exit'
complete -c pg_upgrade -l 'disable-integer-datetimes.'

