# pgrep: Darwin man parser
# Autogenerated from man pages
complete -c pgrep -s F --description 'Restrict matches to a process whose PID is st... [See Man Page]'
complete -c pgrep -s G --description 'Restrict matches to processes with a real gro... [See Man Page]'
complete -c pgrep -s I --description 'Request confirmation before attempting to sig... [See Man Page]'
complete -c pgrep -s L --description The
complete -c pgrep -s P --description 'Restrict matches to processes with a parent p... [See Man Page]'
complete -c pgrep -s U --description 'Restrict matches to processes with a real use... [See Man Page]'
complete -c pgrep -s d --description 'Specify a delimiter to be printed between eac... [See Man Page]'
complete -c pgrep -s a --description 'Include process ancestors in the match list'
complete -c pgrep -s f --description 'Match against full argument lists'
complete -c pgrep -s g --description 'Restrict matches to processes with a process ... [See Man Page]'
complete -c pgrep -s i --description 'Ignore case distinctions in both the process ... [See Man Page]'
complete -c pgrep -s l --description 'Long output'
complete -c pgrep -s n --description 'Select only the newest (most recently started... [See Man Page]'
complete -c pgrep -s o --description 'Select only the oldest (least recently starte... [See Man Page]'
complete -c pgrep -s q --description 'Do not write anything to standard output'
complete -c pgrep -s t --description 'Restrict matches to processes associated with... [See Man Page]'
complete -c pgrep -s u --description 'Restrict matches to processes with an effecti... [See Man Page]'
complete -c pgrep -s v --description 'Reverse the sense of the matching; display pr... [See Man Page]'
complete -c pgrep -s x --description 'Require an exact match of the process name, o... [See Man Page]'
complete -c pgrep -l signal --description 'A non-negative decimal number or symbolic sig... [See Man Page]'

