# pkill: Darwin man parser
# Autogenerated from man pages
complete -c pkill -s F --description 'Restrict matches to a process whose PID is st... [See Man Page]'
complete -c pkill -s G --description 'Restrict matches to processes with a real gro... [See Man Page]'
complete -c pkill -s I --description 'Request confirmation before attempting to sig... [See Man Page]'
complete -c pkill -s L --description The
complete -c pkill -s P --description 'Restrict matches to processes with a parent p... [See Man Page]'
complete -c pkill -s U --description 'Restrict matches to processes with a real use... [See Man Page]'
complete -c pkill -s d --description 'Specify a delimiter to be printed between eac... [See Man Page]'
complete -c pkill -s a --description 'Include process ancestors in the match list'
complete -c pkill -s f --description 'Match against full argument lists'
complete -c pkill -s g --description 'Restrict matches to processes with a process ... [See Man Page]'
complete -c pkill -s i --description 'Ignore case distinctions in both the process ... [See Man Page]'
complete -c pkill -s l --description 'Long output'
complete -c pkill -s n --description 'Select only the newest (most recently started... [See Man Page]'
complete -c pkill -s o --description 'Select only the oldest (least recently starte... [See Man Page]'
complete -c pkill -s q --description 'Do not write anything to standard output'
complete -c pkill -s t --description 'Restrict matches to processes associated with... [See Man Page]'
complete -c pkill -s u --description 'Restrict matches to processes with an effecti... [See Man Page]'
complete -c pkill -s v --description 'Reverse the sense of the matching; display pr... [See Man Page]'
complete -c pkill -s x --description 'Require an exact match of the process name, o... [See Man Page]'
complete -c pkill -l signal --description 'A non-negative decimal number or symbolic sig... [See Man Page]'

