# prune: Deroffing man parser
# Autogenerated from man pages
complete -c prune -s n --description 'Specifies name of node to prune'
complete -c prune -s N --description 'Specifies attribute that will be set (or chan... [See Man Page]'

