# query: Deroffing man parser
# Autogenerated from man pages
complete -c query -o config --description 'config file to use (default /etc/sqlrelay/sql... [See Man Page]'
complete -c query -o id --description 'instance to use (as per config file)'

