# radtest: Deroffing man parser
# Autogenerated from man pages
complete -c radtest -s d --description 'The directory that contains the RADIUS dictio... [See Man Page]'
complete -c radtest -s t --description 'Choose the authentiction method to use'
complete -c radtest -s x --description 'Enables debugging output for the RADIUS clien... [See Man Page]'
complete -c radtest -s 4 --description 'Use NAS-IP-Address for the NAS address (defau... [See Man Page]'
complete -c radtest -s 6 --description 'Use NAS-IPv6-Address for the NAS address (def... [See Man Page]'

