# radzap: Deroffing man parser
# Autogenerated from man pages
complete -c radzap -o draddb_directory --description 'The directory that contains the RADIUS config... [See Man Page]'
complete -c radzap -s h --description 'Print usage help information'
complete -c radzap -o Nnas_ip_address --description 'Zap the entries which match the given NAS IP ... [See Man Page]'
complete -c radzap -o Pnas_port --description 'Zap the entries which match the given NAS por... [See Man Page]'
complete -c radzap -o uuser --description 'Zap the entries which match the given usernam... [See Man Page]'
complete -c radzap -o Uuser --description 'Zap the entries which match the given usernam... [See Man Page]'
complete -c radzap -s x --description 'Enable debugging output'
complete -c radzap -s d --description 'The directory that contains the RADIUS config... [See Man Page]'
complete -c radzap -s N --description 'Zap the entries which match the given NAS IP ... [See Man Page]'
complete -c radzap -s P --description 'Zap the entries which match the given NAS por... [See Man Page]'
complete -c radzap -s u --description 'Zap the entries which match the given usernam... [See Man Page]'
complete -c radzap -s U --description 'Zap the entries which match the given usernam... [See Man Page]'

