# rake: Darwin man parser
# Autogenerated from man pages
complete -c rake -l -version --description 'Display the program version'
complete -c rake -s C
complete -c rake -l -classic-namespace --description 'Put Task and FileTask in the top level namesp... [See Man Page]'
complete -c rake -s D
complete -c rake -l -describe --description 'Describe the tasks (matching optional'
complete -c rake -s E
complete -c rake -l -execute-continue --description 'Execute some Ruby code, then continue with no... [See Man Page]'
complete -c rake -s G
complete -c rake -l -no-system
complete -c rake -l -nosystem --description 'Use standard project Rakefile search paths, i... [See Man Page]'
complete -c rake -s I
complete -c rake -l -libdir --description Include
complete -c rake -s N
complete -c rake -l -no-search
complete -c rake -l -nosearch --description 'Do not search parent directories for the Rake... [See Man Page]'
complete -c rake -s P
complete -c rake -l -prereqs --description 'Display the tasks and dependencies, then exit... [See Man Page]'
complete -c rake -s R
complete -c rake -l -rakelib
complete -c rake -l -rakelibdir --description 'Auto-import any '
complete -c rake -s T
complete -c rake -l -tasks --description 'Display the tasks (matching optional'
complete -c rake -s e
complete -c rake -l -execute --description 'Execute some Ruby code and exit'
complete -c rake -s f
complete -c rake -l -rakefile --description 'Use FILE as the rakefile'
complete -c rake -s h
complete -c rake -l -help --description 'Prints a summary of options'
complete -c rake -s g
complete -c rake -l -system --description 'Using system wide (global) rakefiles (usually... [See Man Page]'
complete -c rake -s n
complete -c rake -l -dry-run --description 'Do a dry run without executing actions'
complete -c rake -s p
complete -c rake -l -execute-print --description 'Execute some Ruby code, print the result, the... [See Man Page]'
complete -c rake -s q
complete -c rake -l -quiet --description 'Do not log messages to standard output'
complete -c rake -s r
complete -c rake -l -require --description 'Require MODULE before executing rakefile'
complete -c rake -s s
complete -c rake -l -silent --description Like
complete -c rake -s t
complete -c rake -l -trace --description 'Turn on invoke/execute tracing, enable full b... [See Man Page]'
complete -c rake -s v
complete -c rake -l -verbose --description 'Log message to standard output (default)'
complete -c rake -l -rules --description 'Trace the rules resolution'

