# rand: Type1
# Autogenerated from man pages
complete -c rand -o out --description 'Write to file instead of standard output'
complete -c rand -o rand --description 'Use specified file or files or \\s-1EGD\\s0 soc... [See Man Page]'
complete -c rand -o base64 --description 'Perform base64 encoding on the output'

