# rcs2log: Darwin man parser
# Autogenerated from man pages
complete -c rcs2log -s c --description 'Output a change log prefix to'
complete -c rcs2log -s h --description Use
complete -c rcs2log -s i --description 'Indent change log lines by'
complete -c rcs2log -s l --description 'Try to limit log lines to'
complete -c rcs2log -s R --description 'If no'
complete -c rcs2log -s r --description Pass
complete -c rcs2log -s t --description 'Tab stops are every'
complete -c rcs2log -s u --description Assume
complete -c rcs2log -s v --description 'Append RCS revision to file names in log line... [See Man Page]'
complete -c rcs2log -l -help --description 'Output help'
complete -c rcs2log -l -version --description 'Output version number'

