# reindexdb: Deroffing man parser
# Autogenerated from man pages
complete -c reindexdb -s a -l all --description 'Reindex all databases'
complete -c reindexdb -s e -l echo --description 'Echo the commands that reindexdb generates an... [See Man Page]'
complete -c reindexdb -s i -l index --description 'Recreate index only'
complete -c reindexdb -s q -l quiet --description 'Do not display progress messages'
complete -c reindexdb -s s -l system --description 'Reindex database\\*(Aqs system catalogs'
complete -c reindexdb -s t -l table --description 'Reindex table only'
complete -c reindexdb -s V -l version --description 'Print the reindexdb version and exit'
complete -c reindexdb -s '?' -l help --description 'Show help about reindexdb command line argume... [See Man Page]'
complete -c reindexdb -s h -l host --description 'Specifies the host name of the machine on whi... [See Man Page]'
complete -c reindexdb -s p -l port --description 'Specifies the TCP port or local Unix domain s... [See Man Page]'
complete -c reindexdb -s U -l username --description 'User name to connect as'
complete -c reindexdb -s w -l no-password --description 'Never issue a password prompt'
complete -c reindexdb -s W -l password --description 'Force reindexdb to prompt for a password befo... [See Man Page]'
complete -c reindexdb -l 'all)' --description PGDATABASE

