# resize: Deroffing man parser
# Autogenerated from man pages
complete -c resize -s u --description 'This option indicates that Bourne shell comma... [See Man Page]'
complete -c resize -s c --description 'This option indicates that C shell commands s... [See Man Page]'
complete -c resize -s s --description 'This option indicates that Sun console escape... [See Man Page]'

