# ruby: Darwin man parser
# Autogenerated from man pages
complete -c ruby -l -copyright --description 'Prints the copyright notice'
complete -c ruby -l -version --description 'Prints the version of Ruby interpreter'
complete -c ruby -s 0 --description '(The digit'
complete -c ruby -s C --description 'Causes Ruby to switch to the directory'
complete -c ruby -s F --description 'Specifies input field separator'
complete -c ruby -s I --description 'Used to tell Ruby where to load the library s... [See Man Page]'
complete -c ruby -s K --description 'Specifies KANJI (Japanese) encoding'
complete -c ruby -s S --description 'Makes Ruby use the'
complete -c ruby -s T --description 'Turns on taint checks at the specified level ... [See Man Page]'
complete -c ruby -s a --description 'Turns on auto-split mode when used with'
complete -c ruby -s c --description 'Causes Ruby to check the syntax of the script... [See Man Page]'
complete -c ruby -s d
complete -c ruby -l -debug --description 'Turns on debug mode'
complete -c ruby -s e --description 'Specifies script from command-line while tell... [See Man Page]'
complete -c ruby -s h
complete -c ruby -l -help --description 'Prints a summary of the options'
complete -c ruby -s i --description 'Specifies in-place-edit mode'
complete -c ruby -s l --description '(The lowercase letter'
complete -c ruby -s n --description 'Causes Ruby to assume the following loop arou... [See Man Page]'
complete -c ruby -s p --description 'Acts mostly same as -n switch, but print the ... [See Man Page]'
complete -c ruby -s r --description 'Causes Ruby to load the library using require... [See Man Page]'
complete -c ruby -s s --description 'Enables some switch parsing for switches afte... [See Man Page]'
complete -c ruby -s v
complete -c ruby -l -verbose --description 'Enables verbose mode'
complete -c ruby -s w --description 'Enables verbose mode without printing version... [See Man Page]'
complete -c ruby -s x --description 'Tells Ruby that the script is embedded in a m... [See Man Page]'
complete -c ruby -s y
complete -c ruby -l -yydebug --description 'Turns on compiler debug mode'

