# rudiments-config: Deroffing man parser
# Autogenerated from man pages
complete -c rudiments-config -l prefix --description 'print prefix'
complete -c rudiments-config -l exec-prefix --description 'print exec-prefix'
complete -c rudiments-config -l version --description 'print rudiments library version'
complete -c rudiments-config -l libs --description 'print libs string for compiling with rudiment... [See Man Page]'
complete -c rudiments-config -l with-rpath --description 'print rpath (if any)'
complete -c rudiments-config -l cflags --description 'print cflags AUTHOR This manual page was writ... [See Man Page]'

