# s_time: Type1
# Autogenerated from man pages
complete -c s_time -o connect --description 'This specifies the host and optional port to ... [See Man Page]'
complete -c s_time -o www --description 'This specifies the page to \\s-1GET\\s0 from th... [See Man Page]'
complete -c s_time -o cert --description 'The certificate to use, if one is requested b... [See Man Page]'
complete -c s_time -o key --description 'The private key to use'
complete -c s_time -o verify --description 'The verify depth to use'
complete -c s_time -o CApath --description 'The directory to use for server certificate v... [See Man Page]'
complete -c s_time -o CAfile --description 'A file containing trusted certificates to use... [See Man Page]'
complete -c s_time -o new --description 'performs the timing test using a new session ... [See Man Page]'
complete -c s_time -o reuse --description 'performs the timing test using the same sessi... [See Man Page]'
complete -c s_time -o nbio --description 'turns on non-blocking I/O'
complete -c s_time -o ssl2 -o ssl3 --description 'these options disable the use of certain \\s-1... [See Man Page]'
complete -c s_time -o bugs --description 'there are several known bug in \\s-1SSL\\s0 and... [See Man Page]'
complete -c s_time -o cipher --description 'this allows the cipher list sent by the clien... [See Man Page]'

