# sccmap: Deroffing man parser
# Autogenerated from man pages
complete -c sccmap -s d --description 'Preserve degenerate components of only one no... [See Man Page]'
complete -c sccmap -s s --description 'Do not print the resulting graphs'
complete -c sccmap -s S --description 'Just print the resulting graphs'
complete -c sccmap -s o --description 'Prints output to the file output'
complete -c sccmap -s v --description 'Generate additional statistics'

