# sessreg: Deroffing man parser
# Autogenerated from man pages
complete -c sessreg -s w --description 'This specifies an alternate wtmp file, instea... [See Man Page]'
complete -c sessreg -s u --description 'This specifies an alternate utmp file, instea... [See Man Page]'
complete -c sessreg -s L --description 'This specifies an alternate lastlog file, ins... [See Man Page]'
complete -c sessreg -s l --description 'This describes the "line" name of the entry'
complete -c sessreg -s h --description 'This is set for BSD hosts to indicate that th... [See Man Page]'
complete -c sessreg -s s --description 'Each potential session has a unique slot numb... [See Man Page]'
complete -c sessreg -s x --description 'As X sessions are one-per-display, and each d... [See Man Page]'
complete -c sessreg -s t --description 'This specifies an alternate file which the -x... [See Man Page]'
complete -c sessreg -s a --description 'This session should be added to utmp/wtmp'
complete -c sessreg -o 't).' --description 'sessreg accepts the BSD-specific flags in the... [See Man Page]'
complete -c sessreg -s d --description 'This session should be deleted from utmp/wtmp... [See Man Page]'

