# setquota: Darwin man parser
# Autogenerated from man pages
complete -c setquota -s a --description 'sets home directory quota for users defined i... [See Man Page]'
complete -c setquota -s l --description 'sets home directory quota for users defined i... [See Man Page]'
complete -c setquota -s n --description 'sets home directory quota for users defined i... [See Man Page]'
complete -c setquota -s u --description 'sets home directory quota for a specific user... [See Man Page]'

