# sfdp: Deroffing man parser
# Autogenerated from man pages
complete -c sfdp -o Tps
complete -c sfdp -o Tsvg -o Tsvgz
complete -c sfdp -o Tfig
complete -c sfdp -o Tmif
complete -c sfdp -o Thpgl -o Tpcl
complete -c sfdp -o Tpng -o Tgif
complete -c sfdp -o Tdia
complete -c sfdp -o Timap --description 'that has a non-null "href" attribute'
complete -c sfdp -o Tcmapx --description 'Additional less common or more special-purpos... [See Man Page]'
complete -c sfdp -s G
complete -c sfdp -s N
complete -c sfdp -s E --description 'Example: -Gsize="7,8" -Nshape=box -Efontsize=... [See Man Page]'
complete -c sfdp -o lfile --description 'Usually these define custom shapes or styles'
complete -c sfdp -o Tlang
complete -c sfdp -o 'n[1' --description 'If set, neato assumes nodes have already been... [See Man Page]'
complete -c sfdp -o Klayout
complete -c sfdp -s O -s T
complete -c sfdp -s P
complete -c sfdp -s v
complete -c sfdp -s V
complete -c sfdp -s '?' --description EXAMPLES

