# sharing: Darwin man parser
# Autogenerated from man pages
complete -c sharing -s a --description 'add a new share point for the directory speci... [See Man Page]'
complete -c sharing -s e --description 'edit the share point record specified by <sha... [See Man Page]'
complete -c sharing -s r --description 'delete the share point record specified by <s... [See Man Page]'
complete -c sharing -s l --description 'list all existing share point records'
complete -c sharing -s A --description 'use customized name <afp name> when using sha... [See Man Page]'
complete -c sharing -s F --description 'use customized name <ftp name> when using sha... [See Man Page]'
complete -c sharing -s S --description 'use customized name <smb name> when using sha... [See Man Page]'
complete -c sharing -s s --description 'use this option to modify individually, the s... [See Man Page]'
complete -c sharing -s g --description 'use this option to modify individually, the "... [See Man Page]'
complete -c sharing -s i --description 'use this option to modify the "inherit privil... [See Man Page]'
complete -c sharing -s n --description 'Specify a <customized record name> to be used... [See Man Page]'

