# showfont: Type1
# Autogenerated from man pages
complete -c showfont -o server --description 'The X font server to contact'
complete -c showfont -o fn --description 'The font to display'
complete -c showfont -o lsb --description 'The bit order of the font should be requested... [See Man Page]'
complete -c showfont -o msb --description 'The bit order of the font should be requested... [See Man Page]'
complete -c showfont -o LSB --description 'The byte order of the font should be requeste... [See Man Page]'
complete -c showfont -o MSB --description 'The byte order of the font should be requeste... [See Man Page]'
complete -c showfont -o 'ext[ents_only]' --description 'Only the character extents should be displaye... [See Man Page]'
complete -c showfont -o start --description 'The start of the range of the characters to d... [See Man Page]'
complete -c showfont -o end --description 'The end of the range of the characters to dis... [See Man Page]'
complete -c showfont -o unit --description 'The scanline unit of the font (8, 16, 32, or ... [See Man Page]'
complete -c showfont -o pad --description 'The scanpad unit of the font (8, 16, 32, or 6... [See Man Page]'
complete -c showfont -o 'b[itmap_pad]' --description 'The bitmap padding unit of the font (0, 1, or... [See Man Page]'

