# smbencrypt: Deroffing man parser
# Autogenerated from man pages
complete -c smbencrypt -l '------------------------------	--------------------------------' --description '5BFAFBEBFB6A0942AAD3B435B51404EE	AC8E657F83DF... [See Man Page]'

