# smproxy: Deroffing man parser
# Autogenerated from man pages
complete -c smproxy -o clientId --description 'Specifies the session ID used by smproxy in t... [See Man Page]'
complete -c smproxy -o restore --description 'Specifies the file used by smproxy to save st... [See Man Page]'

