# start_erl: Deroffing man parser
# Autogenerated from man pages
complete -c start_erl -o reldir --description 'Mandatory if the environment variable RELDIR ... [See Man Page]'
complete -c start_erl -o rootdir --description 'Mandatory if -reldir is not given and there i... [See Man Page]'
complete -c start_erl -o data --description 'Optional, specifies another data file than st... [See Man Page]'
complete -c start_erl -o bootflags --description 'Optional, specifies a file name relative to a... [See Man Page]'

