# stringdups: Darwin man parser
# Autogenerated from man pages
complete -c stringdups -l invertCallTrees --description 'Print call trees from hottest to coldest stac... [See Man Page]'
complete -c stringdups -l nostacks --description 'Do not print call trees even if the target pr... [See Man Page]'

