# tiffset: Deroffing man parser
# Autogenerated from man pages
complete -c tiffset -s d --description 'change the current directory (starting at 0)'
complete -c tiffset -s s --description 'Set the value of the named tag to the value o... [See Man Page]'
complete -c tiffset -o sd --description 'change the current directory by offset'
complete -c tiffset -o sf --description 'Set the value of the tag to the contents of f... [See Man Page]'

