# twm: Deroffing man parser
# Autogenerated from man pages
complete -c twm -o display --description 'This option specifies the X server to use'
complete -c twm -s s --description 'This option indicates that only the default s... [See Man Page]'
complete -c twm -s f --description 'This option specifies the name of the startup... [See Man Page]'
complete -c twm -s v --description 'This option indicates that twm should print e... [See Man Page]'

