# twopi: Deroffing man parser
# Autogenerated from man pages
complete -c twopi -o Tps
complete -c twopi -o Tsvg -o Tsvgz
complete -c twopi -o Tfig
complete -c twopi -o Tmif
complete -c twopi -o Thpgl -o Tpcl
complete -c twopi -o Tpng -o Tgif
complete -c twopi -o Tdia
complete -c twopi -o Timap --description 'that has a non-null "href" attribute'
complete -c twopi -o Tcmapx --description 'Additional less common or more special-purpos... [See Man Page]'
complete -c twopi -s G
complete -c twopi -s N
complete -c twopi -s E --description 'Example: -Gsize="7,8" -Nshape=box -Efontsize=... [See Man Page]'
complete -c twopi -o lfile --description 'Usually these define custom shapes or styles'
complete -c twopi -o Tlang
complete -c twopi -o 'n[1' --description 'If set, neato assumes nodes have already been... [See Man Page]'
complete -c twopi -o Klayout
complete -c twopi -s O -s T
complete -c twopi -s P
complete -c twopi -s v
complete -c twopi -s V
complete -c twopi -s '?' --description EXAMPLES

