# unflatten: Deroffing man parser
# Autogenerated from man pages
complete -c unflatten -s l --description 'The minimum length of leaf edges is staggered... [See Man Page]'
complete -c unflatten -s f --description 'Enables the staggering of the -l option to fa... [See Man Page]'
complete -c unflatten -s c --description 'Form disconnected nodes into chains of up to ... [See Man Page]'
complete -c unflatten -s o --description 'causes the output to be written to the specif... [See Man Page]'

