# uxterm: Deroffing man parser
# Autogenerated from man pages
complete -c uxterm -o class --description and
complete -c uxterm -o u8 --description 'options should not be specified because they ... [See Man Page]'

