# vacuumdb: Deroffing man parser
# Autogenerated from man pages
complete -c vacuumdb -s a -l all --description 'Vacuum all databases'
complete -c vacuumdb -s e -l echo --description 'Echo the commands that vacuumdb generates and... [See Man Page]'
complete -c vacuumdb -s f -l full --description 'Perform \\(lqfull\\(rq vacuuming'
complete -c vacuumdb -s F -l freeze --description 'Aggressively \\(lqfreeze\\(rq tuples'
complete -c vacuumdb -s q -l quiet --description 'Do not display progress messages'
complete -c vacuumdb -s t -l table --description 'Clean or analyze table only'
complete -c vacuumdb -s v -l verbose --description 'Print detailed information during processing'
complete -c vacuumdb -s V -l version --description 'Print the vacuumdb version and exit'
complete -c vacuumdb -s z -l analyze --description 'Also calculate statistics for use by the opti... [See Man Page]'
complete -c vacuumdb -s Z -l analyze-only --description 'Only calculate statistics for use by the opti... [See Man Page]'
complete -c vacuumdb -s '?' -l help --description 'Show help about vacuumdb command line argumen... [See Man Page]'
complete -c vacuumdb -s h -l host --description 'Specifies the host name of the machine on whi... [See Man Page]'
complete -c vacuumdb -s p -l port --description 'Specifies the TCP port or local Unix domain s... [See Man Page]'
complete -c vacuumdb -s U -l username --description 'User name to connect as'
complete -c vacuumdb -s w -l no-password --description 'Never issue a password prompt'
complete -c vacuumdb -s W -l password --description 'Force vacuumdb to prompt for a password befor... [See Man Page]'
complete -c vacuumdb -l 'all)' --description PGDATABASE

