# vacuumlo: Deroffing man parser
# Autogenerated from man pages
complete -c vacuumlo -s l --description 'Remove no more than limit large objects per t... [See Man Page]'
complete -c vacuumlo -s n --description 'Don\\*(Aqt remove anything, just show what wou... [See Man Page]'
complete -c vacuumlo -s v --description 'Write a lot of progress messages'
complete -c vacuumlo -s V -l version --description 'Print the vacuumlo version and exit'
complete -c vacuumlo -s '?' -l help --description 'Show help about vacuumlo command line argumen... [See Man Page]'
complete -c vacuumlo -s h --description 'Database server\\*(Aqs host'
complete -c vacuumlo -s p --description 'Database server\\*(Aqs port'
complete -c vacuumlo -s U --description 'User name to connect as'
complete -c vacuumlo -s w -l no-password --description 'Never issue a password prompt'
complete -c vacuumlo -s W --description 'Force vacuumlo to prompt for a password befor... [See Man Page]'

