# version: Type1
# Autogenerated from man pages
complete -c version -s a --description 'all information, this is the same as setting ... [See Man Page]'
complete -c version -s v --description 'the current OpenSSL version'
complete -c version -s b --description 'the date the current version of OpenSSL was b... [See Man Page]'
complete -c version -s o --description 'option information: various options set when ... [See Man Page]'
complete -c version -s c --description 'compilation flags'
complete -c version -s p --description 'platform setting'

