# viewres: Deroffing man parser
# Autogenerated from man pages
complete -c viewres -o top --description 'This option specifies the name of the highest... [See Man Page]'
complete -c viewres -o variable --description 'This option indicates that the widget variabl... [See Man Page]'
complete -c viewres -o vertical --description 'This option indicates that the tree should be... [See Man Page]'

