# wifidiagnose: Darwin man parser
# Autogenerated from man pages
complete -c wifidiagnose -l scan --description 'scan for Wi-Fi networks using either an '
complete -c wifidiagnose -l tests --description 'run diagnostics tests either '
complete -c wifidiagnose -l monitor --description 'monitor the Wi-Fi '
complete -c wifidiagnose -l time --description 'seconds to monitor performance, events or tra... [See Man Page]'
complete -c wifidiagnose -l browse --description 'browse for and resolve common Bonjour service... [See Man Page]'

