# x11perfcomp: Deroffing man parser
# Autogenerated from man pages
complete -c x11perfcomp -s r --description 'Specifies that the output should also include... [See Man Page]'
complete -c x11perfcomp -o ro --description 'Specifies that the output should include only... [See Man Page]'
complete -c x11perfcomp -s l --description 'Specifies a label file to use'

