# xauth: Deroffing man parser
# Autogenerated from man pages
complete -c xauth -s f --description 'This option specifies the name of the authori... [See Man Page]'
complete -c xauth -s q --description 'This option indicates that xauth should opera... [See Man Page]'
complete -c xauth -s v --description 'This option indicates that xauth should opera... [See Man Page]'
complete -c xauth -s i --description 'This option indicates that xauth should ignor... [See Man Page]'
complete -c xauth -s b --description 'This option indicates that xauth should attem... [See Man Page]'
complete -c xauth -s n --description 'This option indicates that xauth should not a... [See Man Page]'

