# xbacklight: Deroffing man parser
# Autogenerated from man pages
complete -c xbacklight -o get --description 'Print out the current backlight brightness of... [See Man Page]'
complete -c xbacklight -o set --description 'Sets each backlight brightness to the specifi... [See Man Page]'
complete -c xbacklight -o inc --description 'Increases brightness by the specified amount'
complete -c xbacklight -o dec --description 'Decreases brightness by the specified amount'
complete -c xbacklight -o help --description 'Print out a summary of the usage and exit'
complete -c xbacklight -o time --description 'Length of time to spend fading the backlight ... [See Man Page]'
complete -c xbacklight -o steps --description 'Number of steps to take while fading'

