# xcalc: Deroffing man parser
# Autogenerated from man pages
complete -c xcalc -o stipple --description 'This option indicates that the background of ... [See Man Page]'
complete -c xcalc -o rpn --description 'This option indicates that Reverse Polish Not... [See Man Page]'

