# xclipboard: Deroffing man parser
# Autogenerated from man pages
complete -c xclipboard -s w --description 'This option indicates that lines of text that... [See Man Page]'
complete -c xclipboard -o nw --description 'This option indicates that long lines of text... [See Man Page]'

