# xcmsdb: Type1
# Autogenerated from man pages
complete -c xcmsdb -o query --description 'This option attempts to read the XDCCC proper... [See Man Page]'
complete -c xcmsdb -o remove --description 'This option attempts to remove the XDCCC prop... [See Man Page]'

