# xcompmgr: Deroffing man parser
# Autogenerated from man pages
complete -c xcompmgr -s d --description 'Specifies the display to manage'
complete -c xcompmgr -s r --description 'Specifies the blur radius for client-side sha... [See Man Page]'
complete -c xcompmgr -s o --description 'Specifies the opacity for client-side shadows... [See Man Page]'
complete -c xcompmgr -s l --description 'Specifies the left offset for client-side sha... [See Man Page]'
complete -c xcompmgr -s t --description 'Specifies the top offset for client-side shad... [See Man Page]'
complete -c xcompmgr -s I --description 'Specifies the opacity change between steps wh... [See Man Page]'
complete -c xcompmgr -s O --description 'Specifies the opacity change between steps wh... [See Man Page]'
complete -c xcompmgr -s D --description 'Specifies the time (in milliseconds) between ... [See Man Page]'
complete -c xcompmgr -s a --description 'Automatic server-side compositing'
complete -c xcompmgr -s c --description 'Client-side compositing with soft shadows and... [See Man Page]'
complete -c xcompmgr -s f --description 'When -c is specified, enables a smooth fade e... [See Man Page]'
complete -c xcompmgr -s n --description 'Simple client-side compositing'
complete -c xcompmgr -s s --description 'Server-side compositing with hard-edged shado... [See Man Page]'
complete -c xcompmgr -s C --description 'When -c is specified, attempts to avoid paint... [See Man Page]'
complete -c xcompmgr -s F --description 'When -f is specified, also enables the fade e... [See Man Page]'
complete -c xcompmgr -s S --description 'Enables synchronous operation'

