# xconsole: Deroffing man parser
# Autogenerated from man pages
complete -c xconsole -o file --description 'To monitor some other device, use this option... [See Man Page]'
complete -c xconsole -o notify -o nonotify --description 'When new data are received from the console a... [See Man Page]'
complete -c xconsole -o daemon --description 'This option causes  xconsole to place itself ... [See Man Page]'
complete -c xconsole -o verbose --description 'When set, this option directs  xconsole to di... [See Man Page]'
complete -c xconsole -o exitOnFail --description 'When set, this option directs  xconsole to ex... [See Man Page]'
complete -c xconsole -o saveLines --description 'When set, xconsole only preserves count lines... [See Man Page]'

