# xcutsel: Deroffing man parser
# Autogenerated from man pages
complete -c xcutsel -o selection --description 'This option specifies the name of the selecti... [See Man Page]'
complete -c xcutsel -o cutbuffer --description 'This option specifies the cut buffer to use'

