# xditview: Deroffing man parser
# Autogenerated from man pages
complete -c xditview -o page --description 'This option specifies the page number of the ... [See Man Page]'
complete -c xditview -o resolution --description 'This specifies the desired screen resolution ... [See Man Page]'
complete -c xditview -o noPolyText --description 'Some X servers incorrectly implement PolyText... [See Man Page]'
complete -c xditview -o backingStore --description 'Redisplay can take up to a second or so; this... [See Man Page]'
complete -c xditview -o bg --description 'This option specifies the color to use for th... [See Man Page]'
complete -c xditview -o bd --description 'This option specifies the color to use for th... [See Man Page]'
complete -c xditview -o bw --description 'This option specifies the width in pixels of ... [See Man Page]'
complete -c xditview -o fg --description 'This option specifies the color to use for di... [See Man Page]'
complete -c xditview -o fn --description 'This option specifies the font to be used for... [See Man Page]'
complete -c xditview -o rv --description 'This option indicates that reverse video shou... [See Man Page]'
complete -c xditview -o geometry --description 'This option specifies the preferred size and ... [See Man Page]'
complete -c xditview -o display --description 'This option specifies the X server to contact... [See Man Page]'
complete -c xditview -o xrm --description 'This option specifies a resource string to be... [See Man Page]'

