# xdm: Deroffing man parser
# Autogenerated from man pages
complete -c xdm -o config --description 'Names the configuration file, which specifies... [See Man Page]'
complete -c xdm -o nodaemon --description 'Specifies ``false\'\' as the value for the Disp... [See Man Page]'
complete -c xdm -o debug --description 'Specifies the numeric value for the DisplayMa... [See Man Page]'
complete -c xdm -o error --description 'Specifies the value for the DisplayManager'
complete -c xdm -o resources --description 'Specifies the value for the DisplayManager*re... [See Man Page]'
complete -c xdm -o server --description 'Specifies the value for the DisplayManager'
complete -c xdm -o udpPort --description 'Specifies the value for the DisplayManager'
complete -c xdm -o session --description 'Specifies the value for the DisplayManager*se... [See Man Page]'
complete -c xdm -o xrm --description 'Allows an arbitrary resource to be specified,... [See Man Page]'

