# xdpr: Deroffing man parser
# Autogenerated from man pages
complete -c xdpr -o Pprinter --description 'Specifies a printer to send the output to'
complete -c xdpr -o display --description 'Normally,  xdpr gets the host and display num... [See Man Page]'
complete -c xdpr -o device --description 'Specifies the device on which the file will b... [See Man Page]'
complete -c xdpr -o help --description 'This option displays the list of options know... [See Man Page]'

