# Xephyr: Deroffing man parser
# Autogenerated from man pages
complete -c Xephyr -o screen --description 'sets the screen size'
complete -c Xephyr -o parent --description 'uses exiting window  id '
complete -c Xephyr -o host-cursor --description 'set \'cursor acceleration\': The host\'s cursor ... [See Man Page]'

