# xev: Deroffing man parser
# Autogenerated from man pages
complete -c xev -o display --description 'This option specifies the X server to contact... [See Man Page]'
complete -c xev -o geometry --description 'This option specifies the size and/or locatio... [See Man Page]'
complete -c xev -o bw --description 'This option specifies the border width for th... [See Man Page]'
complete -c xev -o bs --description 'This option specifies what kind of backing st... [See Man Page]'
complete -c xev -o id --description 'This option specifies that the window with th... [See Man Page]'
complete -c xev -o root --description 'This option specifies that the root window sh... [See Man Page]'
complete -c xev -s s --description 'This option specifies that save-unders should... [See Man Page]'
complete -c xev -o name --description 'This option specifies the name to assign to t... [See Man Page]'
complete -c xev -o rv --description 'This option specifies that the window should ... [See Man Page]'

