# xeyes: Deroffing man parser
# Autogenerated from man pages
complete -c xeyes -o fg --description 'choose a different color for the pupil of the... [See Man Page]'
complete -c xeyes -o bg --description 'choose a different color for the background'
complete -c xeyes -o outline --description 'choose a different color for the outline of t... [See Man Page]'
complete -c xeyes -o center --description 'choose a different color for the center of th... [See Man Page]'
complete -c xeyes -o backing --description 'selects an appropriate level of backing store... [See Man Page]'
complete -c xeyes -o geometry --description 'define the initial window geometry; see X(7)'
complete -c xeyes -o display --description 'specify the display to use; see X(7)'
complete -c xeyes -o bd --description 'choose a different color for the window borde... [See Man Page]'
complete -c xeyes -o bw --description 'choose a different width for the window borde... [See Man Page]'
complete -c xeyes -o shape --description 'uses the SHAPE extension to shape the window'
complete -c xeyes -o render --description 'uses Xrender to draw anti-aliased eyes'
complete -c xeyes -o distance --description 'uses an alternative mapping, as if the eyes w... [See Man Page]'

