# xfd: Type1
# Autogenerated from man pages
complete -c xfd -o fn --description 'This option specifies the core X server side ... [See Man Page]'
complete -c xfd -o fa --description 'This option specifies a Xft font to be displa... [See Man Page]'
complete -c xfd -o box --description 'This option indicates that a box should be di... [See Man Page]'
complete -c xfd -o center --description 'This option indicates that each glyph should ... [See Man Page]'
complete -c xfd -o start --description 'This option specifies the glyph index of the ... [See Man Page]'
complete -c xfd -o bc --description 'This option specifies the color to be used if... [See Man Page]'
complete -c xfd -o rows --description 'This option specifies the number of rows in t... [See Man Page]'

