# xfs: Deroffing man parser
# Autogenerated from man pages
complete -c xfs -o config --description 'specifies the configuration file  xfs will us... [See Man Page]'
complete -c xfs -o daemon --description 'instructs  xfs to fork and go into the backgr... [See Man Page]'
complete -c xfs -o droppriv --description 'instructs  xfs to attempt to run as user and ... [See Man Page]'
complete -c xfs -o inetd --description 'informs  xfs that it is being started by inet... [See Man Page]'
complete -c xfs -o ls --description 'specifies a file descriptor which is already ... [See Man Page]'
complete -c xfs -o nodaemon --description 'instructs  xfs not to daemonize (fork and det... [See Man Page]'
complete -c xfs -o port --description 'specifies the TCP port number on which the se... [See Man Page]'
complete -c xfs -o user --description 'option is used)'

