# xgamma: Deroffing man parser
# Autogenerated from man pages
complete -c xgamma -o display --description 'This argument allows you to specify the serve... [See Man Page]'
complete -c xgamma -o screen --description 'When multiple displays are configured as a si... [See Man Page]'
complete -c xgamma -o quiet --description 'Silence the normal output of  xgamma '
complete -c xgamma -o help --description 'Print out the `Usage:\' command syntax summary... [See Man Page]'
complete -c xgamma -o gamma --description 'The gamma correction can either be defined as... [See Man Page]'
complete -c xgamma -o rgamma --description 'This argument specifies the red component of ... [See Man Page]'
complete -c xgamma -o ggamma --description 'This argument specifies the green component o... [See Man Page]'
complete -c xgamma -o bgamma --description 'options, xgamma prints the current gamma corr... [See Man Page]'

