# xkbbell: Deroffing man parser
# Autogenerated from man pages
complete -c xkbbell -o display --description 'specifies which display to use'
complete -c xkbbell -o synch --description 'turns on synchronization '
complete -c xkbbell -o dev --description 'specifies which device to use '
complete -c xkbbell -o force --description 'force audible bell '
complete -c xkbbell -o nobeep --description 'suppress server bell, event only '
complete -c xkbbell -o bf --description 'specifies which bell feedback to use '
complete -c xkbbell -o kf --description 'specifies which keyboard feedback to use '
complete -c xkbbell -s v --description 'specifies which volume to use '
complete -c xkbbell -s w --description 'specifies which  window to use'

