# xkbevd: Deroffing man parser
# Autogenerated from man pages
complete -c xkbevd -o help --description 'Prints a usage message that is far more up-to... [See Man Page]'
complete -c xkbevd -o cfg --description 'Specifies the configuration file to read'
complete -c xkbevd -o sccmd --description 'Specifies the command used to play sounds'
complete -c xkbevd -o sddirectory --description 'Specifies a top-level directory for sound fil... [See Man Page]'
complete -c xkbevd -o displaydisplay --description 'Specifies the display to use'
complete -c xkbevd -o bg --description 'Tells xkbevd to fork itself (and run in the b... [See Man Page]'
complete -c xkbevd -o synch --description 'Forces synchronization of all X requests'
complete -c xkbevd -o sc --description 'Specifies the command used to play sounds'
complete -c xkbevd -o sd --description 'Specifies a top-level directory for sound fil... [See Man Page]'
complete -c xkbevd -o display --description 'Specifies the display to use'
complete -c xkbevd -s v --description 'Print more information, including debugging m... [See Man Page]'

