# xkbvleds: Deroffing man parser
# Autogenerated from man pages
complete -c xkbvleds -o indpy --description 'Mask of LEDs to watch'
complete -c xkbvleds -o watch --description 'turn on synchronization '
complete -c xkbvleds -o intersection --description 'Watch only LEDs in all desired sets '
complete -c xkbvleds -o union --description 'Watch LEDs in any desired sets'

