# xkill: Deroffing man parser
# Autogenerated from man pages
complete -c xkill -o display --description 'This option specifies the name of the X serve... [See Man Page]'
complete -c xkill -o id --description 'This option specifies the X identifier for th... [See Man Page]'
complete -c xkill -o button --description 'This option specifies the number of pointer b... [See Man Page]'
complete -c xkill -o all --description 'This option indicates that all clients with t... [See Man Page]'
complete -c xkill -o frame --description 'This option indicates that xkill should ignor... [See Man Page]'

