# xload: Deroffing man parser
# Autogenerated from man pages
complete -c xload -o hl -o highlight --description 'This option specifies the color of the scale ... [See Man Page]'
complete -c xload -o jumpscroll --description 'The number of pixels to shift the graph to th... [See Man Page]'
complete -c xload -o label --description 'The string to put into the label above the lo... [See Man Page]'
complete -c xload -o nolabel --description 'If this command line option is specified then... [See Man Page]'
complete -c xload -o lights --description 'When specified, this option causes  xload to ... [See Man Page]'
complete -c xload -o scale --description 'This option specifies the minimum number of t... [See Man Page]'
complete -c xload -o update --description 'This option specifies the interval in seconds... [See Man Page]'
complete -c xload -o remote --description 'This option tells xload to display the load o... [See Man Page]'

