# xlogo: Deroffing man parser
# Autogenerated from man pages
complete -c xlogo -o render --description 'This option indicates that the logo should be... [See Man Page]'
complete -c xlogo -o sharp --description 'If -render is also specified, this forces the... [See Man Page]'
complete -c xlogo -o shape --description 'This option indicates that the logo window sh... [See Man Page]'

