# xlsatoms: Type1
# Autogenerated from man pages
complete -c xlsatoms -o display --description 'This option specifies the X server to which t... [See Man Page]'
complete -c xlsatoms -o format --description 'This option specifies a printf-style string u... [See Man Page]'
complete -c xlsatoms -o range --description 'This option specifies the range of atom value... [See Man Page]'

