# xlsclients: Deroffing man parser
# Autogenerated from man pages
complete -c xlsclients -o display --description 'This option specifies the X server to contact... [See Man Page]'
complete -c xlsclients -s a --description 'This option indicates that clients on all scr... [See Man Page]'
complete -c xlsclients -s l --description 'List in long format, giving the window name, ... [See Man Page]'
complete -c xlsclients -s m --description 'This option specifies the maximum number of c... [See Man Page]'

