# xlsfonts: Deroffing man parser
# Autogenerated from man pages
complete -c xlsfonts -o display --description 'This option specifies the X server to contact... [See Man Page]'
complete -c xlsfonts -s d --description 'Same as -display host:dpy'
complete -c xlsfonts -s l --description 'Lists some attributes of the font on one line... [See Man Page]'
complete -c xlsfonts -o ll --description 'Lists font properties in addition to -l outpu... [See Man Page]'
complete -c xlsfonts -o lll --description 'Lists character metrics in addition to -ll ou... [See Man Page]'
complete -c xlsfonts -s m --description 'This option indicates that long listings shou... [See Man Page]'
complete -c xlsfonts -s C --description 'This option indicates that listings should us... [See Man Page]'
complete -c xlsfonts -s 1 --description 'This option indicates that listings should us... [See Man Page]'
complete -c xlsfonts -s w --description 'This option specifies the width in characters... [See Man Page]'
complete -c xlsfonts -s n --description 'This option specifies the number of columns t... [See Man Page]'
complete -c xlsfonts -s u --description 'This option indicates that the output should ... [See Man Page]'
complete -c xlsfonts -s o --description 'This option indicates that xlsfonts should do... [See Man Page]'
complete -c xlsfonts -o fn --description 'This option specifies the font name pattern t... [See Man Page]'

