# xmag: Deroffing man parser
# Autogenerated from man pages
complete -c xmag -o source --description 'This option specifies the size and/or locatio... [See Man Page]'
complete -c xmag -o mag --description 'This option indicates the magnification to be... [See Man Page]'

