# xman: Type1
# Autogenerated from man pages
complete -c xman -o helpfile --description 'Specifies a helpfile to use other than the de... [See Man Page]'
complete -c xman -o bothshown --description 'Allows both the manual page and manual direct... [See Man Page]'
complete -c xman -o notopbox --description 'Starts without the Top Menu with the three bu... [See Man Page]'
complete -c xman -o geometry --description 'Sets the size and location of the Top Menu wi... [See Man Page]'

