# xmessage: Deroffing man parser
# Autogenerated from man pages
complete -c xmessage -o buttons --description 'This option will cause xmessage to create one... [See Man Page]'
complete -c xmessage -o default --description 'Defines the button with a matching label to b... [See Man Page]'
complete -c xmessage -o file --description 'File to display'
complete -c xmessage -o print --description 'This will cause the program to write the labe... [See Man Page]'
complete -c xmessage -o center --description 'Pop up the window at the center of the screen... [See Man Page]'
complete -c xmessage -o nearmouse --description 'Pop up the window near the mouse cursor'
complete -c xmessage -o timeout --description 'Exit with status 0 after secs seconds if the ... [See Man Page]'

