# xmh: Deroffing man parser
# Autogenerated from man pages
complete -c xmh -o path --description 'This option specifies an alternate collection... [See Man Page]'
complete -c xmh -o initial --description 'This option specifies an alternate folder whi... [See Man Page]'
complete -c xmh -o flag --description 'This option will cause xmh to change the appe... [See Man Page]'

