# xmodmap: Deroffing man parser
# Autogenerated from man pages
complete -c xmodmap -o display --description 'This option specifies the host and display to... [See Man Page]'
complete -c xmodmap -o help --description 'This option indicates that a brief descriptio... [See Man Page]'
complete -c xmodmap -o grammar --description 'This option indicates that a help message des... [See Man Page]'
complete -c xmodmap -o verbose --description 'This option indicates that   xmodmap should p... [See Man Page]'
complete -c xmodmap -o quiet --description 'This option turns off the verbose logging'
complete -c xmodmap -s n --description 'This option indicates that   xmodmap should n... [See Man Page]'
complete -c xmodmap -s e --description 'This option specifies an expression to be exe... [See Man Page]'
complete -c xmodmap -o pm --description 'This option indicates that the current modifi... [See Man Page]'
complete -c xmodmap -o pk --description 'This option indicates that the current keymap... [See Man Page]'
complete -c xmodmap -o pke --description 'This option indicates that the current keymap... [See Man Page]'
complete -c xmodmap -o pp --description 'This option indicates that the current pointe... [See Man Page]'

