# Xnest: Deroffing man parser
# Autogenerated from man pages
complete -c Xnest -o display --description 'This option specifies the display name of the... [See Man Page]'
complete -c Xnest -o sync --description 'This option tells  Xnest to synchronize its w... [See Man Page]'
complete -c Xnest -o full --description 'This option tells  Xnest to utilize full rege... [See Man Page]'
complete -c Xnest -o class --description 'This option specifies the default visual clas... [See Man Page]'
complete -c Xnest -o depth --description 'This option specifies the default visual dept... [See Man Page]'
complete -c Xnest -o sss --description 'This option tells  Xnest to use the software ... [See Man Page]'
complete -c Xnest -o geometry --description 'This option specifies the geometry parameters... [See Man Page]'
complete -c Xnest -o bw --description 'This option specifies the border width of the... [See Man Page]'
complete -c Xnest -o name --description 'This option specifies the name of the top-lev... [See Man Page]'
complete -c Xnest -o scrns --description 'This option specifies the number of screens t... [See Man Page]'
complete -c Xnest -o install --description 'This option tells  Xnest to do its own color ... [See Man Page]'
complete -c Xnest -o cc --description 'option from the set of standard options excep... [See Man Page]'
complete -c Xnest -o parent --description 'This option tells Xnest to use window_id as t... [See Man Page]'

