# xprop: Deroffing man parser
# Autogenerated from man pages
complete -c xprop -o help --description 'Print out a summary of command line options'
complete -c xprop -o grammar --description 'Print out a detailed grammar for all command ... [See Man Page]'
complete -c xprop -o id --description 'This argument allows the user to select windo... [See Man Page]'
complete -c xprop -o name --description 'This argument allows the user to specify that... [See Man Page]'
complete -c xprop -o font --description 'This argument allows the user to specify that... [See Man Page]'
complete -c xprop -o root --description 'This argument specifies that X\'s root window ... [See Man Page]'
complete -c xprop -o display --description 'This argument allows you to specify the serve... [See Man Page]'
complete -c xprop -o len --description 'Specifies that at most n bytes of any propert... [See Man Page]'
complete -c xprop -o notype --description 'Specifies that the type of each property shou... [See Man Page]'
complete -c xprop -o fs --description 'Specifies that file file should be used as a ... [See Man Page]'
complete -c xprop -o frame --description 'Specifies that when selecting a window by han... [See Man Page]'
complete -c xprop -o remove --description 'Specifies the name of a property to be remove... [See Man Page]'
complete -c xprop -o set --description 'Specifies the name of a property and a proper... [See Man Page]'
complete -c xprop -o spy --description 'Examine window properties forever, looking fo... [See Man Page]'
complete -c xprop -s f --description 'Specifies that the format for name should be ... [See Man Page]'

