# Xquartz: Deroffing man parser
# Autogenerated from man pages
complete -c Xquartz -o fakebuttons --description 'Same as enable_fake_buttons above with value ... [See Man Page]'
complete -c Xquartz -o nofakebuttons --description 'Same as enable_fake_buttons above with value ... [See Man Page]'
complete -c Xquartz -o fakemouse2 --description 'Same as fake_button2 above'
complete -c Xquartz -o fakemouse3 --description 'Same as fake_button3 above'
complete -c Xquartz -o depth --description 'Same as depth above'

