# xrefresh: Deroffing man parser
# Autogenerated from man pages
complete -c xrefresh -o white --description 'Use a white background'
complete -c xrefresh -o black --description 'Use a black background (in effect, turning of... [See Man Page]'
complete -c xrefresh -o solid --description 'Use a solid background of the specified color... [See Man Page]'
complete -c xrefresh -o root --description 'Use the root window background'
complete -c xrefresh -o none --description 'This is the default'
complete -c xrefresh -o geometry --description 'Specifies the portion of the screen to be rep... [See Man Page]'
complete -c xrefresh -o display --description 'This  argument  allows  you  to  specify the ... [See Man Page]'

