# xscope: Deroffing man parser
# Autogenerated from man pages
complete -c xscope -s i --description 'Specify the port that xscope will use to take... [See Man Page]'
complete -c xscope -s o --description 'Determines the port that xscope will use to c... [See Man Page]'
complete -c xscope -s h --description 'Determines the host that  xscope will use to ... [See Man Page]'
complete -c xscope -s d --description 'Defines the display number'
complete -c xscope -s q --description 'Quiet output mode'
complete -c xscope -s v --description 'Determines the level of printing which xscope... [See Man Page]'
complete -c xscope -s r --description 'Print only raw data without decoding it'
complete -c xscope -s D --description 'Print debugging information at the specified ... [See Man Page]'
complete -c xscope -s S --description 'Toggle output on or off when SIGUSR1 is recei... [See Man Page]'
complete -c xscope -s t --description 'Terminate xscope when all clients close'
complete -c xscope -o 'o3).' --description 'SEE ALSO X (7), Xsecurity (7), X11 Protocol a... [See Man Page]'

