# xset: Deroffing man parser
# Autogenerated from man pages
complete -c xset -o display --description 'This option specifies the server to use; see ... [See Man Page]'
complete -c xset -o dpms --description 'The -dpms option disables DPMS (Energy Star) ... [See Man Page]'
complete -c xset -o fp --description 'The -fp and fp- options remove elements from ... [See Man Page]'

