# xsetroot: Deroffing man parser
# Autogenerated from man pages
complete -c xsetroot -o help --description 'Print a usage message and exit'
complete -c xsetroot -o def --description 'Reset unspecified attributes to the default v... [See Man Page]'
complete -c xsetroot -o cursor --description 'This lets you change the pointer cursor to wh... [See Man Page]'
complete -c xsetroot -o cursor_name --description 'This lets you change the pointer cursor to on... [See Man Page]'
complete -c xsetroot -o xcf --description 'This lets you change the pointer cursor to on... [See Man Page]'
complete -c xsetroot -o bitmap --description 'Use the bitmap specified in the file to set t... [See Man Page]'
complete -c xsetroot -o mod --description 'This is used if you want a plaid-like grid pa... [See Man Page]'
complete -c xsetroot -o gray --description 'Make the entire background gray'
complete -c xsetroot -o grey --description 'Make the entire background grey'
complete -c xsetroot -o fg --description 'Use ``color\'\' as the foreground color'
complete -c xsetroot -o bg --description 'Use ``color\'\' as the background color'
complete -c xsetroot -o rv --description 'This exchanges the foreground and background ... [See Man Page]'
complete -c xsetroot -o solid --description 'This sets the background of the root window t... [See Man Page]'
complete -c xsetroot -o name --description 'Set the name of the root window to ``string\'\'... [See Man Page]'
complete -c xsetroot -o display --description 'Specifies the server to connect to; see X(7)'

