# xsm: Deroffing man parser
# Autogenerated from man pages
complete -c xsm -o display --description 'Causes xsm to connect to the specified X disp... [See Man Page]'
complete -c xsm -o session --description 'Causes xsm to load the specified session, byp... [See Man Page]'
complete -c xsm -o verbose --description 'Turns on debugging information'

