# xstdcmap: Deroffing man parser
# Autogenerated from man pages
complete -c xstdcmap -o all --description 'This option indicates that all six standard c... [See Man Page]'
complete -c xstdcmap -o best --description 'This option indicates that the RGB_BEST_MAP s... [See Man Page]'
complete -c xstdcmap -o blue --description 'This option indicates that the RGB_BLUE_MAP s... [See Man Page]'
complete -c xstdcmap -o default --description 'This option indicates that the RGB_DEFAULT_MA... [See Man Page]'
complete -c xstdcmap -o delete --description 'This option specifies that a specific standar... [See Man Page]'
complete -c xstdcmap -o display --description 'This option specifies the host and display to... [See Man Page]'
complete -c xstdcmap -o gray --description 'This option indicates that the RGB_GRAY_MAP s... [See Man Page]'
complete -c xstdcmap -o green --description 'This option indicates that the RGB_GREEN_MAP ... [See Man Page]'
complete -c xstdcmap -o help --description 'This option indicates that a brief descriptio... [See Man Page]'
complete -c xstdcmap -o red --description 'This option indicates that the RGB_RED_MAP sh... [See Man Page]'
complete -c xstdcmap -o verbose --description 'This option indicates that xstdcmap should pr... [See Man Page]'

