# Xvfb: Deroffing man parser
# Autogenerated from man pages
complete -c Xvfb -o screen --description 'This option creates screen screennum and sets... [See Man Page]'
complete -c Xvfb -o pixdepths --description 'This option specifies a list of pixmap depths... [See Man Page]'
complete -c Xvfb -o fbdir --description 'This option specifies the directory in which ... [See Man Page]'
complete -c Xvfb -o shmem --description 'This option specifies that the framebuffer sh... [See Man Page]'
complete -c Xvfb -o linebias --description 'This option specifies how to adjust the pixel... [See Man Page]'
complete -c Xvfb -o blackpixel -o whitepixel --description 'These options specify the black and white pix... [See Man Page]'

