# xvinfo: Deroffing man parser
# Autogenerated from man pages
complete -c xvinfo -o display --description 'This argument allows you to specify the serve... [See Man Page]'
complete -c xvinfo -o short --description 'Output less details, to reduce the amount of ... [See Man Page]'

