# xwd: Deroffing man parser
# Autogenerated from man pages
complete -c xwd -o display --description 'This argument allows you to specify the serve... [See Man Page]'
complete -c xwd -o help --description 'Print out the `Usage:\' command syntax summary... [See Man Page]'
complete -c xwd -o nobdrs --description 'This argument specifies that the window dump ... [See Man Page]'
complete -c xwd -o out --description 'This argument allows the user to explicitly s... [See Man Page]'
complete -c xwd -o xy --description 'This option applies to color displays only'
complete -c xwd -o add --description 'This option specifies an signed value to be a... [See Man Page]'
complete -c xwd -o frame --description 'This option indicates that the window manager... [See Man Page]'
complete -c xwd -o root --description 'This option indicates that the root window sh... [See Man Page]'
complete -c xwd -o id --description 'This option indicates that the window with th... [See Man Page]'
complete -c xwd -o name --description 'This option indicates that the window with th... [See Man Page]'
complete -c xwd -o icmap --description 'Normally the colormap of the chosen window is... [See Man Page]'
complete -c xwd -o screen --description 'This option indicates that the GetImage reque... [See Man Page]'
complete -c xwd -o silent --description 'Operate silently, i'

