# xwud: Deroffing man parser
# Autogenerated from man pages
complete -c xwud -o bg --description 'If a bitmap image (or a single plane of an im... [See Man Page]'
complete -c xwud -o display --description 'This option allows you to specify the server ... [See Man Page]'
complete -c xwud -o dumpheader --description 'This option prints out the XWD header informa... [See Man Page]'
complete -c xwud -o fg --description 'If a bitmap image (or a single plane of an im... [See Man Page]'
complete -c xwud -o geometry --description 'This option allows you to specify the size an... [See Man Page]'
complete -c xwud -o help --description 'Print out a short description of the allowabl... [See Man Page]'
complete -c xwud -o in --description 'This option allows the user to explicitly spe... [See Man Page]'
complete -c xwud -o new --description 'This option forces creation of a new colormap... [See Man Page]'
complete -c xwud -o noclick --description 'Clicking any button in the window will termin... [See Man Page]'
complete -c xwud -o plane --description 'You can select a single bit plane of the imag... [See Man Page]'
complete -c xwud -o raw --description 'This option forces the image to be displayed ... [See Man Page]'
complete -c xwud -o rv --description 'If a bitmap image (or a single plane of an im... [See Man Page]'
complete -c xwud -o scale --description 'Allow the window to be resized, and scale the... [See Man Page]'
complete -c xwud -o std --description 'This option causes the image to be displayed ... [See Man Page]'
complete -c xwud -o vis --description 'This option allows you to specify a particula... [See Man Page]'

