# zfgrep: Darwin man parser
# Autogenerated from man pages
complete -c zfgrep -s A --description Print
complete -c zfgrep -s a --description 'Treat all files as ASCII text'
complete -c zfgrep -s B --description Print
complete -c zfgrep -s b --description 'The offset in bytes of a matched pattern isdi... [See Man Page]'
complete -c zfgrep -s C --description Print
complete -c zfgrep -s c --description 'Only a count of selected lines is written to ... [See Man Page]'
complete -c zfgrep -l colour --description 'Mark up the matching text with the expression... [See Man Page]'
complete -c zfgrep -s D --description 'Specify the demanded action for devices, FIFO... [See Man Page]'
complete -c zfgrep -s d --description 'Specify the demanded action for directories'
complete -c zfgrep -s E --description Interpret
complete -c zfgrep -s e --description 'Specify a pattern used during the search of t... [See Man Page]'
complete -c zfgrep -l exclude --description 'If specified, it excludes files matching the ... [See Man Page]'
complete -c zfgrep -l exclude-dir --description If
complete -c zfgrep -s F --description Interpret
complete -c zfgrep -s f --description 'Read one or more newline separated patterns f... [See Man Page]'
complete -c zfgrep -s G --description Interpret
complete -c zfgrep -s H --description 'Always print filename headers with output lin... [See Man Page]'
complete -c zfgrep -s h --description 'Never print filename headers'
complete -c zfgrep -l help --description 'Print a brief help message'
complete -c zfgrep -s I --description 'Ignore binary files'
complete -c zfgrep -s i --description 'Perform case insensitive matching'
complete -c zfgrep -l include --description 'If specified, only files matching thegiven fi... [See Man Page]'
complete -c zfgrep -l include-dir --description If
complete -c zfgrep -l J --description 'Decompress the'
complete -c zfgrep -s L --description 'Only the names of files not containing select... [See Man Page]'
complete -c zfgrep -s l --description 'Only the names of files containing selected l... [See Man Page]'
complete -c zfgrep -l mmap --description Use
complete -c zfgrep -s m --description 'Stop reading the file after'
complete -c zfgrep -s n --description 'Each output line is preceded by its relative ... [See Man Page]'
complete -c zfgrep -l null --description 'Prints a zero-byte after the file name'
complete -c zfgrep -s O --description If
complete -c zfgrep -l o --description 'Prints only the matching part of the lines'
complete -c zfgrep -s p --description If
complete -c zfgrep -s q --description 'Quiet mode:suppress normal output'
complete -c zfgrep -s R --description 'Recursively search subdirectories listed'
complete -c zfgrep -s S --description If
complete -c zfgrep -s s --description 'Silent mode'
complete -c zfgrep -s U --description 'Search binary files, but do not attempt to pr... [See Man Page]'
complete -c zfgrep -s V --description 'Display version information and exit'
complete -c zfgrep -s v --description 'Selected lines are those'
complete -c zfgrep -s w --description 'The expression is searched for as a word (as ... [See Man Page]'
complete -c zfgrep -s x --description 'Only input lines selected against an entire f... [See Man Page]'
complete -c zfgrep -s y --description 'Equivalent to'
complete -c zfgrep -s Z --description Force
complete -c zfgrep -l binary-files --description 'Controls searching and printing of binary fil... [See Man Page]'
complete -c zfgrep -l context
complete -c zfgrep -l line-buffered --description 'Force output to be line buffered'

