# zgrep: Darwin man parser
# Autogenerated from man pages
complete -c zgrep -s A --description Print
complete -c zgrep -s a --description 'Treat all files as ASCII text'
complete -c zgrep -s B --description Print
complete -c zgrep -s b --description 'The offset in bytes of a matched pattern isdi... [See Man Page]'
complete -c zgrep -s C --description Print
complete -c zgrep -s c --description 'Only a count of selected lines is written to ... [See Man Page]'
complete -c zgrep -l colour --description 'Mark up the matching text with the expression... [See Man Page]'
complete -c zgrep -s D --description 'Specify the demanded action for devices, FIFO... [See Man Page]'
complete -c zgrep -s d --description 'Specify the demanded action for directories'
complete -c zgrep -s E --description Interpret
complete -c zgrep -s e --description 'Specify a pattern used during the search of t... [See Man Page]'
complete -c zgrep -l exclude --description 'If specified, it excludes files matching the ... [See Man Page]'
complete -c zgrep -l exclude-dir --description If
complete -c zgrep -s F --description Interpret
complete -c zgrep -s f --description 'Read one or more newline separated patterns f... [See Man Page]'
complete -c zgrep -s G --description Interpret
complete -c zgrep -s H --description 'Always print filename headers with output lin... [See Man Page]'
complete -c zgrep -s h --description 'Never print filename headers'
complete -c zgrep -l help --description 'Print a brief help message'
complete -c zgrep -s I --description 'Ignore binary files'
complete -c zgrep -s i --description 'Perform case insensitive matching'
complete -c zgrep -l include --description 'If specified, only files matching thegiven fi... [See Man Page]'
complete -c zgrep -l include-dir --description If
complete -c zgrep -l J --description 'Decompress the'
complete -c zgrep -s L --description 'Only the names of files not containing select... [See Man Page]'
complete -c zgrep -s l --description 'Only the names of files containing selected l... [See Man Page]'
complete -c zgrep -l mmap --description Use
complete -c zgrep -s m --description 'Stop reading the file after'
complete -c zgrep -s n --description 'Each output line is preceded by its relative ... [See Man Page]'
complete -c zgrep -l null --description 'Prints a zero-byte after the file name'
complete -c zgrep -s O --description If
complete -c zgrep -l o --description 'Prints only the matching part of the lines'
complete -c zgrep -s p --description If
complete -c zgrep -s q --description 'Quiet mode:suppress normal output'
complete -c zgrep -s R --description 'Recursively search subdirectories listed'
complete -c zgrep -s S --description If
complete -c zgrep -s s --description 'Silent mode'
complete -c zgrep -s U --description 'Search binary files, but do not attempt to pr... [See Man Page]'
complete -c zgrep -s V --description 'Display version information and exit'
complete -c zgrep -s v --description 'Selected lines are those'
complete -c zgrep -s w --description 'The expression is searched for as a word (as ... [See Man Page]'
complete -c zgrep -s x --description 'Only input lines selected against an entire f... [See Man Page]'
complete -c zgrep -s y --description 'Equivalent to'
complete -c zgrep -s Z --description Force
complete -c zgrep -l binary-files --description 'Controls searching and printing of binary fil... [See Man Page]'
complete -c zgrep -l context
complete -c zgrep -l line-buffered --description 'Force output to be line buffered'

